[debug] Created tunnel using local port: '43649'

[debug] SERVER: "127.0.0.1:43649"

[debug] Original chart version: ""
[debug] CHART PATH: /home/matt/go/src/k8s.io/charts/stable/factorio

NAME:   hasty-orangutan
REVISION: 1
RELEASED: Sat Jun  2 15:00:18 2018
CHART: factorio-0.3.1
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
factorio:
  user:
    password: your.password
    username: your.username
factorioServer:
  allowCommands: admins-only
  autosave:
    interval: 2
    slots: 3
  description: Factorio running on Kubernetes
  isPublic: false
  maxPlayers: 255
  name: Kubernetes Server
  noAutoPause: "false"
  port: 34197
  rcon:
    enabled: false
    password: ""
    port: 27015
    serviceType: LoadBalancer
  serviceType: LoadBalancer
  verifyIdentity: false
image: quay.io/games_on_k8s/factorio
imageTag: 0.14.22
persistence:
  mods:
    enabled: false
    size: 128Mi
  savedGames:
    enabled: true
    size: 1Gi
resources:
  requests:
    cpu: 500m
    memory: 512Mi

HOOKS:
MANIFEST:

---
# Source: factorio/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: hasty-orangutan-factorio
  labels:
    app: hasty-orangutan-factorio
    chart: "factorio-0.3.1"
    release: "hasty-orangutan"
    heritage: "Tiller"
type: Opaque
data:
  server-password: ""
  rcon-password: ""
  factorio-username: "eW91ci51c2VybmFtZQ=="
  factorio-password: "eW91ci5wYXNzd29yZA=="
---
# Source: factorio/templates/saves-pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hasty-orangutan-factorio-savedgames
  labels:
    app: hasty-orangutan-factorio
    chart: "factorio-0.3.1"
    release: "hasty-orangutan"
    heritage: "Tiller"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
---
# Source: factorio/templates/factorio-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: hasty-orangutan-factorio
  labels:
    app: hasty-orangutan-factorio
    chart: "factorio-0.3.1"
    release: "hasty-orangutan"
    heritage: "Tiller"
spec:
  type: LoadBalancer
  ports:
  - name: factorio
    port: 34197
    targetPort: factorio
    protocol: UDP
  selector:
    app: hasty-orangutan-factorio
---
# Source: factorio/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hasty-orangutan-factorio
  labels:
    app: hasty-orangutan-factorio
    chart: "factorio-0.3.1"
    release: "hasty-orangutan"
    heritage: "Tiller"
spec:
  template:
    metadata:
      labels:
        app: hasty-orangutan-factorio
    spec:
      containers:
      - name: hasty-orangutan-factorio
        image: "quay.io/games_on_k8s/factorio:0.14.22"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          
        env:
        - name: FACTORIO_SERVER_NAME
          value: "Kubernetes Server"
        - name: FACTORIO_DESCRIPTION
          value: "Factorio running on Kubernetes"
        - name: FACTORIO_PORT
          value: "34197"
        - name: FACTORIO_MAX_PLAYERS
          value: "255"
        - name: FACTORIO_IS_PUBLIC
          value: "false"
        - name: FACTORIO_REQUIRE_USER_VERIFICATION
          value: "false"
        - name: FACTORIO_ALLOW_COMMANDS
          value: "admins-only"
        - name: FACTORIO_NO_AUTO_PAUSE
          value: "false"
        - name: FACTORIO_AUTOSAVE_INTERVAL
          value: "2"
        - name: FACTORIO_AUTOSAVE_SLOTS
          value: "3"

        ports:
        - name: factorio
          containerPort: 34197
          protocol: UDP
        volumeMounts:
        - name: saves
          mountPath: /opt/factorio/saves
        - name: mods
          mountPath: /opt/factorio/mods
      volumes:
      - name: saves
        persistentVolumeClaim:
          claimName: hasty-orangutan-factorio-savedgames
      - name: mods
        emptyDir: {}
