
---
# Source: keycloak-proxy/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mortal-lemur-keycloak-proxy
  labels:
    app: keycloak-proxy
    chart: keycloak-proxy-0.0.1
    release: mortal-lemur
    heritage: Tiller
data:
  proxy.json: |
    {
       "target-url":"http://url-to-the-target-server.example.com",
       "bind-address":"0.0.0.0",
       "http-port":"8080",
       "applications":[
          {
             "base-path":"/",
             "adapter-config":{
                "realm":"REALM_NAME",
                "auth-server-url":"http://url-to-keycloak.example.com/auth",
                "ssl-required":"external",
                "resource":"CLIENT_ID",
                "credentials": {
                  "secret": "CLIENT_SECRET"
                }
             },
             "constraints":[
               {
                  "pattern":"/admin",
                  "roles-allowed":[
                    "admin"
                  ]
               }
             ],
             "proxy-address-forwarding": true
          }
       ]
    }
---
# Source: keycloak-proxy/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mortal-lemur-keycloak-proxy
  labels:
    app: keycloak-proxy
    chart: keycloak-proxy-0.0.1
    release: mortal-lemur
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: keycloak-proxy
    release: mortal-lemur
  sessionAffinity: None
---
# Source: keycloak-proxy/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mortal-lemur-keycloak-proxy
  labels:
    app: keycloak-proxy
    chart: keycloak-proxy-0.0.1
    release: mortal-lemur
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-proxy
      release: mortal-lemur
  template:
    metadata:
      labels:
        app: keycloak-proxy
        release: mortal-lemur
    spec:
      containers:
        - name: keycloak-proxy
          image: "jboss/keycloak-proxy:3.4.2.Final"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {}
            
          volumeMounts:
            - mountPath: /opt/jboss/conf
              name: proxy-config
      volumes:
        - name: proxy-config
          configMap:
            defaultMode: 420
            name: mortal-lemur-keycloak-proxy
