[debug] Created tunnel using local port: '35325'

[debug] SERVER: "127.0.0.1:35325"

[debug] Original chart version: ""
[debug] CHART PATH: /home/matt/go/src/k8s.io/charts/incubator/burrow

NAME:   eating-emu
REVISION: 1
RELEASED: Sat Jun  2 14:58:57 2018
CHART: burrow-0.3.3
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
chain:
  extraSeeds: []
  id: simpleTestChain
  logLevel: info
  name: simpleTestChain
  numberOfNodes: 1
env: {}
extraArgs: {}
genesisFile: eyJnZW5lc2lzX3RpbWUiOiIyMDE3LTEyLTA4VDEwOjEwOjQ5Ljc4MloiLCJjaGFpbl9pZCI6InNpbXBsZVRlc3RDaGFpbiIsInBhcmFtcyI6eyJnbG9iYWxfcGVybWlzc2lvbnMiOnsiYmFzZSI6eyJwZXJtcyI6MjMwMiwic2V0IjoxNjM4M30sInJvbGVzIjpbXX19LCJhY2NvdW50cyI6W3siYWRkcmVzcyI6IjgzRjBEMTk5NzhGQjFDMkFBNzc2MUUxQ0Q2QUZCOTQxNzYxRkE2NUQiLCJhbW91bnQiOjk5OTk5OTk5OTk5OTk5LCJuYW1lIjoic2ltcGxldGVzdGNoYWluX2Z1bGxfMDAwIiwicGVybWlzc2lvbnMiOnsiYmFzZSI6eyJwZXJtcyI6MTYzODMsInNldCI6MTYzODN9LCJyb2xlcyI6W119fV0sInZhbGlkYXRvcnMiOlt7InB1Yl9rZXkiOlsxLCJENEU4MTRBMjFFMjU2QkZGQTNENzkyOEI4N0Q0NDU1OUJGOTQzN0YzMzg2REI4MUMyNDk0RUM4RDVGN0QzMDkwIl0sImFtb3VudCI6OTk5OTk5OTk5OSwibmFtZSI6InNpbXBsZXRlc3RjaGFpbl9mdWxsXzAwMCIsInVuYm9uZF90byI6W3siYWRkcmVzcyI6IjgzRjBEMTk5NzhGQjFDMkFBNzc2MUUxQ0Q2QUZCOTQxNzYxRkE2NUQiLCJhbW91bnQiOjk5OTk5OTk5OTl9XX1dfQ==
image:
  pullPolicy: IfNotPresent
  repository: quay.io/monax/db
  tag: 0.17.1
ingress:
  enabled: false
keysFiles:
  key-000: eyJhZGRyZXNzIjoiODNGMEQxOTk3OEZCMUMyQUE3NzYxRTFDRDZBRkI5NDE3NjFGQTY1RCIsInB1Yl9rZXkiOlsxLCJENEU4MTRBMjFFMjU2QkZGQTNENzkyOEI4N0Q0NDU1OUJGOTQzN0YzMzg2REI4MUMyNDk0RUM4RDVGN0QzMDkwIl0sInByaXZfa2V5IjpbMSwiMkVGMjNDRTE0MkFGMEEwNUY0MzY1NzY3NTk5MzA4QkUzOUNBODBBODg2N0M1OTQxMzAwMjc0MjJEQjY2OTU3OUQ0RTgxNEEyMUUyNTZCRkZBM0Q3OTI4Qjg3RDQ0NTU5QkY5NDM3RjMzODZEQjgxQzI0OTRFQzhENUY3RDMwOTAiXSwibGFzdF9oZWlnaHQiOjAsImxhc3Rfcm91bmQiOjAsImxhc3Rfc3RlcCI6MH0=
nodeSelector: {}
organization: myOrg
persistence:
  enabled: false
podAnnotations: {}
podLabels: {}
resources: null
service:
  api:
    loadBalance: true
    port: 1337
    type: ClusterIP
  peer:
    port: 46656
    type: ClusterIP
  rpc:
    loadBalance: false
    node: "000"
    port: 46657
    type: ClusterIP
tolerations: []

HOOKS:
MANIFEST:

---
# Source: burrow/templates/secret-genesis.yaml
kind: Secret
apiVersion: v1
metadata:
  labels:
    app: burrow
    chart: "burrow-0.3.3"
    heritage: Tiller
    release: eating-emu
  name: eating-emu-burrow-genesis
type: Opaque
data:
  genesis.json: eyJnZW5lc2lzX3RpbWUiOiIyMDE3LTEyLTA4VDEwOjEwOjQ5Ljc4MloiLCJjaGFpbl9pZCI6InNpbXBsZVRlc3RDaGFpbiIsInBhcmFtcyI6eyJnbG9iYWxfcGVybWlzc2lvbnMiOnsiYmFzZSI6eyJwZXJtcyI6MjMwMiwic2V0IjoxNjM4M30sInJvbGVzIjpbXX19LCJhY2NvdW50cyI6W3siYWRkcmVzcyI6IjgzRjBEMTk5NzhGQjFDMkFBNzc2MUUxQ0Q2QUZCOTQxNzYxRkE2NUQiLCJhbW91bnQiOjk5OTk5OTk5OTk5OTk5LCJuYW1lIjoic2ltcGxldGVzdGNoYWluX2Z1bGxfMDAwIiwicGVybWlzc2lvbnMiOnsiYmFzZSI6eyJwZXJtcyI6MTYzODMsInNldCI6MTYzODN9LCJyb2xlcyI6W119fV0sInZhbGlkYXRvcnMiOlt7InB1Yl9rZXkiOlsxLCJENEU4MTRBMjFFMjU2QkZGQTNENzkyOEI4N0Q0NDU1OUJGOTQzN0YzMzg2REI4MUMyNDk0RUM4RDVGN0QzMDkwIl0sImFtb3VudCI6OTk5OTk5OTk5OSwibmFtZSI6InNpbXBsZXRlc3RjaGFpbl9mdWxsXzAwMCIsInVuYm9uZF90byI6W3siYWRkcmVzcyI6IjgzRjBEMTk5NzhGQjFDMkFBNzc2MUUxQ0Q2QUZCOTQxNzYxRkE2NUQiLCJhbW91bnQiOjk5OTk5OTk5OTl9XX1dfQ==
---
# Source: burrow/templates/secret-keys.yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: burrow
    chart: "burrow-0.3.3"
    heritage: Tiller
    release: eating-emu
  name: eating-emu-burrow-keys
type: Opaque
data:
  key-000: eyJhZGRyZXNzIjoiODNGMEQxOTk3OEZCMUMyQUE3NzYxRTFDRDZBRkI5NDE3NjFGQTY1RCIsInB1Yl9rZXkiOlsxLCJENEU4MTRBMjFFMjU2QkZGQTNENzkyOEI4N0Q0NDU1OUJGOTQzN0YzMzg2REI4MUMyNDk0RUM4RDVGN0QzMDkwIl0sInByaXZfa2V5IjpbMSwiMkVGMjNDRTE0MkFGMEEwNUY0MzY1NzY3NTk5MzA4QkUzOUNBODBBODg2N0M1OTQxMzAwMjc0MjJEQjY2OTU3OUQ0RTgxNEEyMUUyNTZCRkZBM0Q3OTI4Qjg3RDQ0NTU5QkY5NDM3RjMzODZEQjgxQzI0OTRFQzhENUY3RDMwOTAiXSwibGFzdF9oZWlnaHQiOjAsImxhc3Rfcm91bmQiOjAsImxhc3Rfc3RlcCI6MH0=
---
# Source: burrow/templates/config-configs.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: burrow
    chart: "burrow-0.3.3"
    heritage: Tiller
    release: eating-emu
  name: eating-emu-burrow-config-000
data:
  config.toml: |-
    [chain]
    assert_chain_id = "simpleTestChain"
    major_version = 0
    minor_version = 17
    genesis_file = "genesis.json"
      [chain.consensus]
      name = "tendermint"
      major_version = 0
      minor_version = 8
      relative_root = "tendermint"
      [chain.manager]
      name = "burrowmint"
      major_version = 0
      minor_version = 17
      relative_root = "burrowmint"
    [servers]
      [servers.bind]
      address = ""
      port = 1337
      [servers.tls]
      tls = false
      cert_path = ""
      key_path = ""
      [servers.cors]
      enable = false
      allow_origins = []
      allow_credentials = false
      allow_methods = []
      allow_headers = []
      expose_headers = []
      max_age = 0
      [servers.http]
      json_rpc_endpoint = "/rpc"
      [servers.websocket]
      endpoint = "/socketrpc"
      max_sessions = 50
      read_buffer_size = 4096
      write_buffer_size = 4096
      [servers.tendermint]
      rpc_local_address = "0.0.0.0:46657"
      endpoint = "/websocket"
      [servers.logging]
      console_log_level = "info"
      file_log_level = "warn"
      log_file = "burrow-logs.log"
    [tendermint]
    private_validator_file = "priv_validator.json"
      [tendermint.configuration]
      moniker = "myOrg-simpleTestChain-validator-000"
      seeds = "eating-emu-burrow-peer-000:46656"
      fast_sync = true
      db_backend = "leveldb"
      log_level = "info"
      node_laddr = "tcp://0.0.0.0:46656"
      rpc_laddr = "tcp://0.0.0.0:46657"
      proxy_app = "tcp://127.0.0.1:46658"
        [tendermint.configuration.p2p]
        dial_timeout_seconds = 1
        handshake_timeout_seconds = 5
        max_num_peers = 20
        authenticated_encryption = true
        send_rate = 512000
        recv_rate = 512000
        fuzz_enable = false # use the fuzz wrapped conn
        fuzz_active = false # toggle fuzzing
        fuzz_mode = "drop"  # eg. drop, delay
        fuzz_max_delay_milliseconds = 3000
        fuzz_prob_drop_rw = 0.2
        fuzz_prob_drop_conn = 0.00
        fuzz_prob_sleep = 0.00
    [burrowmint]
    db_backend = "leveldb"
    tendermint_host = "0.0.0.0:46657"
    [logging]
      [logging.root_sink]
        [logging.root_sink.transform]
          transform_type = "filter"
          filter_mode = "exclude_when_all_match"
          [[logging.root_sink.transform.predicates]]
            key_regex = "log_channel"
            value_regex = "Trace"
        [[logging.root_sink.sinks]]
          [logging.root_sink.sinks.output]
            output_type = "stderr"
            format = "json"
---
# Source: burrow/templates/service-api.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app:  burrow
    chart: burrow-0.3.3
    release: eating-emu
    heritage: Tiller
  name: eating-emu-burrow-api
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
    - name: api
      port: 1337
      targetPort: api
      protocol: TCP
  selector:
    app: burrow
    release: eating-emu
---
# Source: burrow/templates/service-peers.yaml
kind: Service
apiVersion: v1
metadata:
  labels:
    app: burrow
    chart: burrow-0.3.3
    release: eating-emu
    heritage: Tiller
    nodeNumber: "000"
  name: eating-emu-burrow-peer-000
spec:
  type: ClusterIP
  ports:
    - name: peer
      port: 46656
      targetPort: peer
      protocol: TCP
  selector:
    app: burrow
    release: eating-emu
    nodeNumber: "000"
---
# Source: burrow/templates/service-rpc.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: burrow
    chart: burrow-0.3.3
    release: eating-emu
    heritage: Tiller
  name:  eating-emu-burrow-rpc
spec:
  type: ClusterIP
  ports:
    - name: rpc
      port: 46657
      targetPort: rpc
      protocol: TCP
  selector:
    app: burrow
    release: eating-emu
    nodeNumber: "000"
---
# Source: burrow/templates/deployments.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: burrow
    chart: "burrow-0.3.3"
    heritage: Tiller
    release: eating-emu
  name: eating-emu-burrow-000
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: burrow
        release: eating-emu
        nodeNumber: "000"
    spec:
      initContainers:
        - name: init-node
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
            - 'sh'
            - '-xc'
            - 'echo Initializing...; sleep 0; echo Ready to go!'
        - name: init-dir
          image: busybox
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /work
              name: work-dir
            - mountPath: /ref
              name: ref-dir
          command:
            - 'sh'
            - '-xc'
            - 'cp /ref/config.toml /work/; cp /ref/genesis.json /work/; cp /ref/priv_validator.json /work/'
      containers:
        - name: node-000
          image: "quay.io/monax/db:0.17.1"
          imagePullPolicy: IfNotPresent
          args:
          env:
            - name: BURROW_WORKDIR
              value: /work
            - name: BURROW_DATADIR
              value: /data
          volumeMounts:
            - mountPath: /work
              name: work-dir
            - mountPath: /data
              name: data-dir
          ports:
            - name: peer
              protocol: TCP
              containerPort: 46656
            - name: rpc
              protocol: TCP
              containerPort: 46657
            - name: api
              protocol: TCP
              containerPort: 1337
          livenessProbe:
            httpGet:
              path: /status
              port: rpc
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /status
              port: rpc
              scheme: HTTP
            initialDelaySeconds: 1
      volumes:
        - name: ref-dir
          projected:
            sources:
              - configMap:
                  name: eating-emu-burrow-config-000
                  items:
                    - key: config.toml
                      path: config.toml
              - secret:
                  name: eating-emu-burrow-genesis
                  items:
                    - key: genesis.json
                      path: genesis.json
              - secret:
                  name: eating-emu-burrow-keys
                  items:
                    - key: key-000
                      path: priv_validator.json
        - name: work-dir
          emptyDir: {}
        - name: data-dir
          emptyDir: {}
      securityContext:
        fsGroup: 101
        runAsUser: 1000
      tolerations:
        []
