
---
# Source: eventrouter/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: auxilliary-chicken-eventrouter
  labels:     
    app: eventrouter
    heritage: Tiller
    release: auxilliary-chicken
    chart: eventrouter-0.1.0
data:
apiVersion: v1
data:
  config.json: |- 
    {
      "sink": "glog"
    }
---
# Source: eventrouter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:     
    app: eventrouter
    heritage: Tiller
    release: auxilliary-chicken
    chart: eventrouter-0.1.0
  name: auxilliary-chicken-eventrouter
---
# Source: eventrouter/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:     
    app: eventrouter
    heritage: Tiller
    release: auxilliary-chicken
    chart: eventrouter-0.1.0
  name: auxilliary-chicken-eventrouter
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
---
# Source: eventrouter/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:     
    app: eventrouter
    heritage: Tiller
    release: auxilliary-chicken
    chart: eventrouter-0.1.0
  name: auxilliary-chicken-eventrouter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: auxilliary-chicken-eventrouter
subjects:
  - kind: ServiceAccount
    name: auxilliary-chicken-eventrouter
    namespace: default
---
# Source: eventrouter/templates/deployment.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:     
    app: eventrouter
    heritage: Tiller
    release: auxilliary-chicken
    chart: eventrouter-0.1.0
  name: auxilliary-chicken-eventrouter
spec:
  replicas: 
  selector:
    matchLabels:
      app: eventrouter
      release: auxilliary-chicken    
  template:
    metadata:
      labels:
        app: eventrouter
        release: auxilliary-chicken    
    spec:
      containers:
      - name: eventrouter
        image: "gcr.io/heptio-images/eventrouter:v0.2"
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: config-volume
            mountPath: /etc/eventrouter
        resources:
          {}
          
      serviceAccountName: auxilliary-chicken-eventrouter
      volumes:
        - name: config-volume
          configMap:
            name: auxilliary-chicken-eventrouter
