
---
# Source: fluent-bit/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "intended-eagle-fluent-bit-es-tls-secret"
  labels:
    app: intended-eagle-fluent-bit
type: Opaque
data:
  es-tls-ca.crt: ""
---
# Source: fluent-bit/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: intended-eagle-fluent-bit-config
  labels:
    app: intended-eagle-fluent-bit
data:
  fluent-bit.conf: |-
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name             tail
        Path             /var/log/containers/*.log
        Parser           docker
        Tag              kube.*
        Refresh_Interval 5
        Mem_Buf_Limit    5MB
        Skip_Long_Lines  On

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token

    [OUTPUT]
        Name          forward
        Match         *
        Host          fluentd
        Port          24284
        Retry_Limit False

  parsers.conf: |-
---
# Source: fluent-bit/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: fluent-bit
    chart: fluent-bit-0.5.2
    heritage: Tiller
    release: intended-eagle
  name: intended-eagle-fluent-bit
---
# Source: fluent-bit/templates/cluster-role.yaml
apiVersion: "rbac.authorization.k8s.io/v1"
kind: ClusterRole
metadata:
  labels:
    app: fluent-bit
    chart: fluent-bit-0.5.2
    heritage: Tiller
    release: intended-eagle
  name: intended-eagle-fluent-bit
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
---
# Source: fluent-bit/templates/cluster-rolebinding.yaml
apiVersion: "rbac.authorization.k8s.io/v1"
kind: ClusterRoleBinding
metadata:
  labels:
    app: fluent-bit
    chart: fluent-bit-0.5.2
    heritage: Tiller
    release: intended-eagle
  name: intended-eagle-fluent-bit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: intended-eagle-fluent-bit
subjects:
  - kind: ServiceAccount
    name: intended-eagle-fluent-bit
    namespace: default
---
# Source: fluent-bit/templates/daemonset.yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluent-bit
  labels:
    app: intended-eagle-fluent-bit
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: intended-eagle-fluent-bit
      annotations:
        checksum/config: 901c5c4ea3d23a2019dd4ca4de5d532033fc3432e5c25c4651de37eaa4833c3e
    spec:
      serviceAccountName: intended-eagle-fluent-bit
      containers:
      - name: fluent-bit
        image: "fluent/fluent-bit:0.13.0"
        imagePullPolicy: "Always"
        env:
          []
          
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
          
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config
          mountPath: /fluent-bit/etc/fluent-bit.conf
          subPath: fluent-bit.conf

      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config
        configMap:
          name: intended-eagle-fluent-bit-config
