
---
# Source: kibana/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kibana
    chart: kibana-0.6.0
    release: yummy-crab
    heritage: Tiller
  name: yummy-crab-kibana
  annotations:
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 5601
      protocol: TCP
  selector:
    app: kibana
    release: yummy-crab
---
# Source: kibana/templates/deployment.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: kibana
    chart: "kibana-0.6.0"
    heritage: Tiller
    release: yummy-crab
  name: yummy-crab-kibana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
        release: "yummy-crab"
    spec:
      containers:
      - name: kibana
        image: "docker.elastic.co/kibana/kibana-oss:6.0.0"
        imagePullPolicy: IfNotPresent
        env:
        ports:
        - containerPort: 5601
          name: kibana
          protocol: TCP
        # livenessProbe:
        #   httpGet:
        #     path: /ping
        #     port: 5601
        # readinessProbe:
        #   httpGet:
        #     path: /ping
        #     port: 5601
        resources:
          {}
          
      tolerations:
        []
