
---
# Source: percona/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: wanton-lemur-percona
  labels:
    app: wanton-lemur-percona
    chart: "percona-0.3.2"
    release: "wanton-lemur"
    heritage: "Tiller"
type: Opaque
data:
  
  mysql-root-password: "QmdFUDZ2Z3lWNQ=="
  
  
  mysql-password: "ZTRyS2dMUG45cw=="
---
# Source: percona/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: wanton-lemur-percona
  labels:
    app: wanton-lemur-percona
    chart: "percona-0.3.2"
    release: "wanton-lemur"
    heritage: "Tiller"
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: wanton-lemur-percona
---
# Source: percona/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wanton-lemur-percona
  labels:
    app: wanton-lemur-percona
    chart: "percona-0.3.2"
    release: "wanton-lemur"
    heritage: "Tiller"
spec:
  template:
    metadata:
      labels:
        app: wanton-lemur-percona
    spec:
      initContainers:
      - name: "remove-lost-found"
        image: "busybox:1.25.0" 
        imagePullPolicy: "IfNotPresent"
        command: 
        - "rm"
        - "-fr"
        - "/var/lib/mysql/lost+found"
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      containers:
      - name: wanton-lemur-percona
        image: "mysql:5.7.17"
        imagePullPolicy: "IfNotPresent"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wanton-lemur-percona
              key: mysql-root-password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wanton-lemur-percona
              key: mysql-password
        - name: MYSQL_USER
          value: ""
        - name: MYSQL_DATABASE
          value: ""
        ports:
        - name: mysql
          containerPort: 3306
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      volumes:
      - name: data
        emptyDir: {}
