
---
# Source: check-mk/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: quelling-gecko-check-mk
  labels:
    app: check-mk
    chart: check-mk-0.2.1
    release: quelling-gecko
    heritage: Tiller
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: check-mk
  selector:
    app: check-mk
    release: quelling-gecko
---
# Source: check-mk/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: quelling-gecko-check-mk
  labels:
    app: check-mk
    chart: check-mk-0.2.1
    release: quelling-gecko
    heritage: Tiller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: check-mk
        release: quelling-gecko
    spec:
      containers:
        - name: check-mk
          image: "nlmacamp/check_mk:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /
              port: 5000
          readinessProbe:
            httpGet:
              path: /
              port: 5000
          resources:
            {}
