
---
# Source: prometheus-to-sd/templates/deployment.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ignorant-octopus
  labels:
    app: prometheus-to-sd
    chart: prometheus-to-sd-0.1.0
    release: ignorant-octopus
    heritage: Tiller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus-to-sd
        release: ignorant-octopus
    spec:
      containers:
        - name: prometheus-to-sd
          image: "gcr.io/google-containers/prometheus-to-sd:v0.2.2"
          imagePullPolicy: IfNotPresent
          ports:
            - name: profiler
              containerPort: 6060
          command:
            - /monitor
            - --stackdriver-prefix=custom.googleapis.com
          resources:
            {}
