
---
# Source: filebeat/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: incindiary-seahorse-filebeat
  labels:
    app: filebeat
    chart: filebeat-0.3.0
    release: incindiary-seahorse
    heritage: Tiller
type: Opaque
data:
  filebeat.yml: ICAgIGZpbGViZWF0LmNvbmZpZzoKICAgICAgbW9kdWxlczoKICAgICAgICBwYXRoOiAke3BhdGguY29uZmlnfS9tb2R1bGVzLmQvKi55bWwKICAgICAgICByZWxvYWQuZW5hYmxlZDogZmFsc2UKICAgICAgcHJvc3BlY3RvcnM6CiAgICAgICAgcGF0aDogJHtwYXRoLmNvbmZpZ30vcHJvc3BlY3RvcnMuZC8qLnltbAogICAgICAgIHJlbG9hZC5lbmFibGVkOiBmYWxzZQogICAgZmlsZWJlYXQucHJvc3BlY3RvcnM6CiAgICAtIGVuYWJsZWQ6IHRydWUKICAgICAgcGF0aHM6CiAgICAgIC0gL3Zhci9sb2cvKi5sb2cKICAgICAgdHlwZTogbG9nCiAgICAtIGNvbnRhaW5lcnMuaWRzOgogICAgICAtICcqJwogICAgICBwcm9jZXNzb3JzOgogICAgICAtIGFkZF9rdWJlcm5ldGVzX21ldGFkYXRhOgogICAgICAgICAgaW5fY2x1c3RlcjogdHJ1ZQogICAgICAtIGRyb3BfZXZlbnQ6CiAgICAgICAgICB3aGVuOgogICAgICAgICAgICBlcXVhbHM6CiAgICAgICAgICAgICAga3ViZXJuZXRlcy5jb250YWluZXIubmFtZTogZmlsZWJlYXQKICAgICAgdHlwZTogZG9ja2VyCiAgICBodHRwLmVuYWJsZWQ6IGZhbHNlCiAgICBodHRwLnBvcnQ6IDUwNjYKICAgIG91dHB1dC5maWxlOgogICAgICBmaWxlbmFtZTogZmlsZWJlYXQKICAgICAgbnVtYmVyX29mX2ZpbGVzOiA1CiAgICAgIHBhdGg6IC91c3Ivc2hhcmUvZmlsZWJlYXQvZGF0YQogICAgICByb3RhdGVfZXZlcnlfa2I6IDEwMDAwCiAgICBwcm9jZXNzb3JzOgogICAgLSBhZGRfY2xvdWRfbWV0YWRhdGE6IG51bGwKICAgIA==
---
# Source: filebeat/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: incindiary-seahorse-filebeat
  labels:
    app: filebeat
    chart: filebeat-0.3.0
    release: incindiary-seahorse
    heritage: Tiller
---
# Source: filebeat/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: incindiary-seahorse-filebeat
  labels:
    app: filebeat
    chart: filebeat-0.3.0
    release: incindiary-seahorse
    heritage: Tiller
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  verbs: ["get", "list", "watch"]
---
# Source: filebeat/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: incindiary-seahorse-filebeat
  labels:
    app: filebeat
    chart: filebeat-0.3.0
    release: incindiary-seahorse
    heritage: Tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: incindiary-seahorse-filebeat
subjects:
- kind: ServiceAccount
  name: incindiary-seahorse-filebeat
  namespace: default
---
# Source: filebeat/templates/daemonset.yaml
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: incindiary-seahorse-filebeat
  labels:
    app: filebeat
    chart: filebeat-0.3.0
    release: incindiary-seahorse
    heritage: Tiller
spec:
  selector:
    matchLabels:
      app: filebeat
      release: incindiary-seahorse
  minReadySeconds: 10
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: filebeat
        release: incindiary-seahorse
      annotations:
        checksum/secret: 314177c967b0a3def894c419fe9e8767d1a87a8915d545df555ae1f79621058a
    spec:
      containers:
      - name: filebeat
        image: "docker.elastic.co/beats/filebeat:6.2.3"
        imagePullPolicy: IfNotPresent
        args:
        - "-e"
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
        resources:
          {}
          
        volumeMounts:
        - name: filebeat-config
          mountPath: /usr/share/filebeat/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: filebeat-config
        secret:
          secretName: incindiary-seahorse-filebeat
      - name: data
        hostPath:
          path: /var/lib/filebeat
          type: DirectoryOrCreate
      terminationGracePeriodSeconds: 60
      serviceAccountName: incindiary-seahorse-filebeat
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
