
---
# Source: weave-cloud/templates/secret.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: weave-cloud
data:
  token:
---
# Source: weave-cloud/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: early-owl-weave-cloud
  labels:
    app: weave-cloud
    chart: weave-cloud-0.2.2
    release: early-owl
    heritage: Tiller
---
# Source: weave-cloud/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: early-owl-weave-cloud
  labels:
    app: weave-cloud
    chart: weave-cloud-0.2.2
    release: early-owl
    heritage: Tiller
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'
---
# Source: weave-cloud/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: early-owl-weave-cloud
  labels:
    app: weave-cloud
    chart: weave-cloud-0.2.2
    release: early-owl
    heritage: Tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: early-owl-weave-cloud
subjects:
  - name: early-owl-weave-cloud
    namespace: "default"
    kind: ServiceAccount
---
# Source: weave-cloud/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: weave-agent
  labels:
    app: weave-cloud
    chart: weave-cloud-0.2.2
    release: early-owl
    heritage: Tiller
spec:
  minReadySeconds: 30
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: weave-cloud
      release: early-owl
  template:
    metadata:
      labels:
        app: weave-cloud
        release: early-owl
    spec:
      serviceAccountName: early-owl-weave-cloud
      terminationGracePeriodSeconds: 30
      containers:
      - name: weave-agent
        image: "quay.io/weaveworks/launcher-agent:1.0.0"
        imagePullPolicy: IfNotPresent
        args:
        - -agent.poll-url=https://get.weave.works/k8s/agent.yaml?instanceID={{.InstanceID}}
        - -wc.hostname=cloud.weave.works
        - -wc.token=$(WEAVE_CLOUD_TOKEN)
        env:
        - name: WEAVE_CLOUD_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: weave-cloud
