
---
# Source: dmarc2logstash/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: exiled-cheetah-dmarc2logstash-config
  labels:
    app: dmarc2logstash
    chart: dmarc2logstash-1.0.0
    heritage: Tiller
    release: exiled-cheetah
data:
  filebeat.yml: |
    filebeat.registry_file: /tmp/filebeat_registry
    filebeat.prospectors:
    - type: log
      enabled: true
      paths:
        - "/app/log/forward/*.log"
      json.keys_under_root: true
      json.add_error_key: true
      fields_under_root: true
      fields:
        source_type: 
    output.logstash:
      hosts: 
        - :5000
      index: dmarc
      timeout: 15

    logging.level: info
