
---
# Source: signalfx-agent/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: hopping-wolverine-signalfx-agent
  labels:
    app: signalfx-agent
    chart: signalfx-agent-0.1.1
    heritage: Tiller
    release: hopping-wolverine
type: Opaque
data:
  access-token: ""
---
# Source: signalfx-agent/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: signalfx-agent
    chart: signalfx-agent-0.1.1
    heritage: Tiller
    release: hopping-wolverine
  name: hopping-wolverine-signalfx-agent
---
# Source: signalfx-agent/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hopping-wolverine-signalfx-agent
  labels:
    app: signalfx-agent
    heritage: Tiller
    release: hopping-wolverine
    chart: signalfx-agent-0.1.1
rules:
- apiGroups:
  - ""
  resources:
  - events
  - namespaces
  - namespaces/status
  - nodes
  - nodes/spec
  - pods
  - pods/status
  - replicationcontrollers
  - replicationcontrollers/status
  - services
  # Only need to be able to view secrets if using k8s annotation
  # agent.signalfx.com/configWithSecret.*.  You can also whitelist specific
  # secrets for finer-grain permission sets.
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - update
  - create
- apiGroups:
  - ""
  resources:
  - nodes/stats
  verbs:
  - get
  - list
  # We need create because kubelet takes a POST for the stat query
  - create
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - daemonsets
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch
---
# Source: signalfx-agent/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hopping-wolverine-signalfx-agent
  labels:
    app: signalfx-agent
    heritage: Tiller
    release: hopping-wolverine
    chart: signalfx-agent-0.1.1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hopping-wolverine-signalfx-agent
subjects:
- kind: ServiceAccount
  name: hopping-wolverine-signalfx-agent
  namespace: default
