[debug] Created tunnel using local port: '34843'

[debug] SERVER: "127.0.0.1:34843"

[debug] Original chart version: ""
[debug] CHART PATH: /home/matt/go/src/k8s.io/charts/stable/docker-registry

NAME:   fallacious-seal
REVISION: 1
RELEASED: Sat Jun  2 15:00:16 2018
CHART: docker-registry-1.4.2
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
configData:
  health:
    storagedriver:
      enabled: true
      interval: 10s
      threshold: 3
  http:
    addr: :5000
    headers:
      X-Content-Type-Options:
      - nosniff
  log:
    fields:
      service: registry
  storage:
    cache:
      blobdescriptor: inmemory
  version: 0.1
image:
  pullPolicy: IfNotPresent
  repository: registry
  tag: 2.6.2
ingress:
  annotations: null
  enabled: false
  hosts:
  - chart-example.local
  path: /
  tls: null
persistence:
  accessMode: ReadWriteOnce
  enabled: false
  size: 10Gi
podAnnotations: {}
replicaCount: 1
resources: {}
secrets:
  haSharedSecret: ""
  htpasswd: ""
service:
  annotations: {}
  name: registry
  port: 5000
  type: ClusterIP
storage: filesystem
updateStrategy: null

HOOKS:
MANIFEST:

---
# Source: docker-registry/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: fallacious-seal-docker-registry-secret
  labels:
    app: docker-registry
    chart: docker-registry-1.4.2
    heritage: Tiller
    release: fallacious-seal
type: Opaque
data:
  haSharedSecret: "aGhISjJESmU0UjlEZzJPUg=="
---
# Source: docker-registry/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: fallacious-seal-docker-registry-config
  labels:
    app: docker-registry
    chart: docker-registry-1.4.2
    heritage: Tiller
    release: fallacious-seal
data:
  config.yml: |-
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
    http:
      addr: :5000
      headers:
        X-Content-Type-Options:
        - nosniff
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
    version: 0.1
---
# Source: docker-registry/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fallacious-seal-docker-registry
  labels:
    app: docker-registry
    chart: docker-registry-1.4.2
    release: fallacious-seal
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 5000
      protocol: TCP
      name: registry
      targetPort: 5000
  selector:
    app: docker-registry
    release: fallacious-seal
---
# Source: docker-registry/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fallacious-seal-docker-registry
  labels:
    app: docker-registry
    chart: docker-registry-1.4.2
    release: fallacious-seal
    heritage: Tiller
spec:
  replicas: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: docker-registry
        release: fallacious-seal
      annotations:
        checksum/config: 2b06b1c0d1429571a7ac6dba0c44c6a57349d98b122d37a6f8dbc72ef8a095fa
    spec:
      containers:
        - name: docker-registry
          image: "registry:2.6.2"
          imagePullPolicy: IfNotPresent
          command:
          - /bin/registry
          - serve
          - /etc/docker/registry/config.yml
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /
              port: 5000
          readinessProbe:
            httpGet:
              path: /
              port: 5000
          resources:
            {}
            
          env:
            - name: REGISTRY_HTTP_SECRET
              valueFrom:
                secretKeyRef:
                  name: fallacious-seal-docker-registry-secret
                  key: haSharedSecret
            - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
              value: "/var/lib/registry"
          volumeMounts:
            - name: data
              mountPath: /var/lib/registry/
            - name: "fallacious-seal-docker-registry-config"
              mountPath: "/etc/docker/registry"
      volumes:
        - name: data
          emptyDir: {}
        - name: fallacious-seal-docker-registry-config
          configMap:
            name: fallacious-seal-docker-registry-config
