[debug] Created tunnel using local port: '39171'

[debug] SERVER: "127.0.0.1:39171"

[debug] Original chart version: ""
[debug] CHART PATH: /home/matt/go/src/k8s.io/charts/incubator/cassandra

NAME:   zooming-marsupial
REVISION: 1
RELEASED: Sat Jun  2 14:58:57 2018
CHART: cassandra-0.4.0
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
affinity: {}
config:
  cluster_name: cassandra
  cluster_size: 3
  dc_name: DC1
  endpoint_snitch: SimpleSnitch
  heap_new_size: 512M
  max_heap_size: 2048M
  num_tokens: 256
  ports:
    cql: 9042
    thrift: 9160
  rack_name: RAC1
  seed_size: 2
  start_rpc: false
image:
  pullPolicy: IfNotPresent
  repo: cassandra
  tag: "3"
persistence:
  accessMode: ReadWriteOnce
  enabled: true
  size: 10Gi
podLabels: {}
podManagementPolicy: OrderedReady
podSettings:
  terminationGracePeriodSeconds: 30
resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 2
    memory: 4Gi
securityContext:
  enabled: false
  fsGroup: 999
  runAsUser: 999
service:
  type: ClusterIP
updateStrategy:
  type: OnDelete

HOOKS:
MANIFEST:

---
# Source: cassandra/templates/cassandra-statefulset.yaml
apiVersion: v1
kind: Service
metadata:
  name: zooming-marsupial-cassandra
  labels:
    app: cassandra
    chart: cassandra-0.4.0
    release: zooming-marsupial
    heritage: Tiller
spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - name: intra
    port: 7000
    targetPort: 7000
  - name: tls
    port: 7001
    targetPort: 7001
  - name: jmx
    port: 7199
    targetPort: 7199
  - name: cql
    port: 9042
    targetPort: 9042
  - name: thrift
    port: 9160
    targetPort: 9160
  selector:
    app: cassandra
    release: zooming-marsupial
---
# Source: cassandra/templates/cassandra-statefulset.yaml
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zooming-marsupial-cassandra
  labels:
    app: cassandra
    chart: cassandra-0.4.0
    release: zooming-marsupial
    heritage: Tiller
spec:
  serviceName: zooming-marsupial-cassandra
  replicas: 3
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: OnDelete
  template:
    metadata:
      labels:
        app: cassandra
        release: zooming-marsupial
    spec:
      containers:
      - name: zooming-marsupial-cassandra
        image: "cassandra:3"
        imagePullPolicy: "IfNotPresent"
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 2
            memory: 4Gi
          
        env:
        - name: CASSANDRA_SEEDS
          value: "zooming-marsupial-cassandra-0.zooming-marsupial-cassandra.default.svc.cluster.local,zooming-marsupial-cassandra-1.zooming-marsupial-cassandra.default.svc.cluster.local,"
        - name: MAX_HEAP_SIZE
          value: "2048M"
        - name: HEAP_NEWSIZE
          value: "512M"
        - name: CASSANDRA_ENDPOINT_SNITCH
          value: "SimpleSnitch"
        - name: CASSANDRA_CLUSTER_NAME
          value: "cassandra"
        - name: CASSANDRA_DC
          value: "DC1"
        - name: CASSANDRA_RACK
          value: "RAC1"
        - name: CASSANDRA_START_RPC
          value: "false"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          exec:
            command: [ "/bin/sh", "-c", "nodetool status" ]
          initialDelaySeconds: 90
          periodSeconds: 30
        readinessProbe:
          exec:
            command: [ "/bin/sh", "-c", "nodetool status | grep -E \"^UN\\s+${POD_IP}\"" ]
          initialDelaySeconds: 90
          periodSeconds: 30
        ports:
        - name: intra
          containerPort: 7000
        - name: tls
          containerPort: 7001
        - name: jmx
          containerPort: 7199
        - name: cql
          containerPort: 9042
        - name: thrift
          containerPort: 9160
        volumeMounts:
        - name: data
          mountPath: /var/lib/cassandra
      terminationGracePeriodSeconds: 30
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: cassandra
        chart: cassandra-0.4.0
        release: zooming-marsupial
        heritage: Tiller
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: "10Gi"
