
---
# Source: stackdriver-exporter/templates/service.yaml
kind: Service
apiVersion: v1
metadata:
  name: juiced-pig-stackdriver-exporter
  labels:
    chart: stackdriver-exporter-0.0.4
    app: stackdriver-exporter
    release: "juiced-pig"
    heritage: "Tiller"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9255
      protocol: TCP
  selector:
    app: stackdriver-exporter
    release: "juiced-pig"
---
# Source: stackdriver-exporter/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: juiced-pig-stackdriver-exporter
  labels:
    chart: stackdriver-exporter-0.0.4
    app: stackdriver-exporter
    release: "juiced-pig"
    heritage: "Tiller"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stackdriver-exporter
      release: "juiced-pig"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: stackdriver-exporter
        release: "juiced-pig"
    spec:
      restartPolicy: Always
      containers:
        - name: stackdriver-exporter
          image: "frodenas/stackdriver-exporter:v0.5.1"
          imagePullPolicy: IfNotPresent
          command: ["stackdriver_exporter"]
          env:
            - name: STACKDRIVER_EXPORTER_GOOGLE_PROJECT_ID
              value: "FALSE"
            - name: STACKDRIVER_EXPORTER_MONITORING_METRICS_TYPE_PREFIXES
              value: "compute.googleapis.com/instance/cpu"
            - name: STACKDRIVER_EXPORTER_MONITORING_METRICS_INTERVAL
              value: "5m"
            - name: STACKDRIVER_EXPORTER_MONITORING_METRICS_OFFSET
              value: "0s"
            - name: STACKDRIVER_EXPORTER_WEB_LISTEN_ADDRESS
              value: ":9255"
            - name: STACKDRIVER_EXPORTER_WEB_TELEMETRY_PATH
              value: "/metrics"
          resources:
            {}
            
          ports:
            - containerPort: 9255
              name: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 10
