
---
# Source: coscale/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: coscale
  labels:
    app: coscale
    chart: "coscale-0.2.1"
    release: "quaffing-sloth"
    heritage: "Tiller"
type: Opaque
data:
 app_id : "TUlTU0lORw=="
 access_token : "TUlTU0lORw=="
