[debug] Created tunnel using local port: '46797'

[debug] SERVER: "127.0.0.1:46797"

[debug] Original chart version: ""
[debug] CHART PATH: /home/matt/go/src/k8s.io/charts/stable/zeppelin

NAME:   laughing-lightningbug
REVISION: 1
RELEASED: Sat Jun  2 15:00:39 2018
CHART: zeppelin-1.0.1
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
hadoop:
  configMapName: hadoop-hadoop
  configPath: /usr/hadoop-2.7.3/etc/hadoop
  useConfigMap: false
spark:
  driverMemory: 1g
  executorMemory: 1g
  numExecutors: 2
zeppelin:
  image: dylanmei/zeppelin:0.7.2
  resources:
    limits:
      cpu: 2000m
      memory: 4096Mi

HOOKS:
MANIFEST:

---
# Source: zeppelin/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: laughing-lightningbug-zeppelin
  labels:
    app: zeppelin
    chart: zeppelin-1.0.1
    release: laughing-lightningbug
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
  - port: 8080
    name: web
  selector:
    app: zeppelin
    release: laughing-lightningbug
---
# Source: zeppelin/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: laughing-lightningbug-zeppelin
  labels:
    app: zeppelin
    chart: zeppelin-1.0.1
    release: laughing-lightningbug
    heritage: Tiller
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: zeppelin
        release: laughing-lightningbug
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: zeppelin
          image: dylanmei/zeppelin:0.7.2
          ports:
            - containerPort: 8080
              name: web
          env:
            - name: ZEPPELIN_PORT
              value: "8080"
            - name: ZEPPELIN_JAVA_OPTS
              value: >-
                -Dspark.driver.memory=1g
                -Dspark.executor.memory=1g
          volumeMounts:
          resources:
            limits:
              cpu: 2000m
              memory: 4096Mi
             
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 1
