[debug] Created tunnel using local port: '40675'

[debug] SERVER: "127.0.0.1:40675"

[debug] Original chart version: ""
[debug] CHART PATH: /home/matt/go/src/k8s.io/charts/stable/nginx-lego

NAME:   fair-grasshopper
REVISION: 1
RELEASED: Sat Jun  2 15:00:28 2018
CHART: nginx-lego-0.3.1
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
default:
  image:
    pullPolicy: IfNotPresent
    repository: k8s.gcr.io/defaultbackend
    tag: "1.0"
  replicaCount: 1
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 1
      memory: 128Mi
lego:
  configmap:
    email: my@email.tld
    url: 'https://acme-staging.api.letsencrypt.org/directory '
  enabled: false
  image:
    pullPolicy: IfNotPresent
    repository: jetstack/kube-lego
    tag: 0.1.3
  replicaCount: 1
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 1
      memory: 128Mi
nginx:
  configmap:
    body_size: 64m
    enable_vts_status: "false"
    hsts_include_subdomains: "false"
    proxy_connect_timeout: "30"
    proxy_read_timeout: "600"
    proxy_send_imeout: "600"
    server_name_hash_bucket_size: "256"
  image:
    pullPolicy: IfNotPresent
    repository: k8s.gcr.io/nginx-ingress-controller
    tag: 0.8.3
  monitoring: false
  replicaCount: 1
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 1
      memory: 128Mi
  service:
    type: LoadBalancer

HOOKS:
MANIFEST:

---
# Source: nginx-lego/templates/nginx-configmap.yaml
apiVersion: v1
data:
  proxy-connect-timeout: "30"
  proxy-read-timeout: "600"
  proxy-send-imeout: "600"
  hsts-include-subdomains: "false"
  body-size: "64m"
  server-name-hash-bucket-size: "256"
  enable-vts-status: "false"
kind: ConfigMap
metadata:
  name: fair-grasshopper-nginx-l
---
# Source: nginx-lego/templates/default-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fair-grasshopper-nginx-l-default-backend
  labels:
    chart: "nginx-lego-0.3.1"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: fair-grasshopper-nginx-l-default-backend
---
# Source: nginx-lego/templates/nginx-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fair-grasshopper-nginx-l
  labels:
    chart: "nginx-lego-0.3.1"
spec:
  type: "LoadBalancer"
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    app: fair-grasshopper-nginx-l
---
# Source: nginx-lego/templates/default-deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fair-grasshopper-nginx-l-default-backend
  labels:
    chart: "nginx-lego-0.3.1"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fair-grasshopper-nginx-l-default-backend
    spec:
      containers:
      - name: fair-grasshopper-nginx-l-default-backend
        image: "k8s.gcr.io/defaultbackend:1.0"
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 1
            memory: 128Mi
---
# Source: nginx-lego/templates/nginx-deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fair-grasshopper-nginx-l
  labels:
    chart: "nginx-lego-0.3.1"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fair-grasshopper-nginx-l
    spec:
      containers:
      - name: nginx-lego
        image: "k8s.gcr.io/nginx-ingress-controller:0.8.3"
        imagePullPolicy: IfNotPresent
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 1
            memory: 128Mi
          
        args:
        - /nginx-ingress-controller
        - --default-backend-service=default/fair-grasshopper-nginx-l-default-backend
        - --nginx-configmap=default/fair-grasshopper-nginx-l
