[debug] Created tunnel using local port: '42925'

[debug] SERVER: "127.0.0.1:42925"

[debug] Original chart version: ""
[debug] CHART PATH: /home/matt/go/src/k8s.io/charts/stable/heapster

NAME:   ulterior-oyster
REVISION: 1
RELEASED: Sat Jun  2 15:00:20 2018
CHART: heapster-0.3.0
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
annotations: {}
command:
- /heapster
- --source=kubernetes.summary_api:''
env: []
eventer:
  enabled: false
  flags:
  - --source=kubernetes:https://kubernetes.default
  - --sink=log
  resizer:
    enabled: true
    flags:
    - --cpu=150m
    - --extra-cpu=10m
    - --memory=200Mi
    - --extra-memory=6Mi
    - --threshold=5
    - --poll-period=300000
    resources: {}
  resources: {}
image:
  pullPolicy: IfNotPresent
  repository: k8s.gcr.io/heapster
  tag: v1.3.0
labels: {}
nodeSelector: {}
podAnnotations: {}
rbac:
  create: true
  serviceAccountName: default
replicaCount: 1
resizer:
  enabled: true
  flags:
  - --cpu=150m
  - --extra-cpu=10m
  - --memory=200Mi
  - --extra-memory=6Mi
  - --threshold=5
  - --poll-period=300000
  image:
    pullPolicy: IfNotPresent
    repository: k8s.gcr.io/addon-resizer
    tag: 1.7
  resources:
    limits:
      cpu: 50m
      memory: 90Mi
    requests:
      cpu: 50m
      memory: 90Mi
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
service:
  annotations: {}
  externalPort: 8082
  internalPort: 8082
  labels: null
  type: ClusterIP

HOOKS:
MANIFEST:

---
# Source: heapster/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: heapster
    chart: heapster-0.3.0
    heritage: Tiller
    release: ulterior-oyster
  name: ulterior-oyster-heapster
---
# Source: heapster/templates/heapster-crb.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: heapster
    chart: heapster-0.3.0
    heritage: Tiller
    release: ulterior-oyster
  name: ulterior-oyster-heapster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:heapster
subjects:
  - kind: ServiceAccount
    name: ulterior-oyster-heapster
    namespace: default
---
# Source: heapster/templates/pod-nanny-role.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: ulterior-oyster-heapster-pod-nanny
  labels:
    app: heapster
    chart: heapster-0.3.0
    heritage: Tiller
    release: ulterior-oyster
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - "extensions"
  resources:
  - deployments
  verbs:
  - get
  - update
---
# Source: heapster/templates/pod-nanny-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: ulterior-oyster-heapster-pod-nanny
  labels:
    app: heapster
    chart: heapster-0.3.0
    heritage: Tiller
    release: ulterior-oyster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ulterior-oyster-heapster-pod-nanny
subjects:
- kind: ServiceAccount
  name: ulterior-oyster-heapster
  namespace: default
---
# Source: heapster/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: heapster
  labels:
    chart: "heapster-0.3.0"
    app: ulterior-oyster-heapster
    heritage: "Tiller"
    release: "ulterior-oyster"
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
  selector:
    app: ulterior-oyster-heapster
---
# Source: heapster/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ulterior-oyster-heapster
  annotations:
    {}
    
  labels:
    chart: "heapster-0.3.0"
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        {}
        
      labels:
        app: ulterior-oyster-heapster
    spec:
      serviceAccountName: ulterior-oyster-heapster
      containers:
      - name: heapster
        image: "k8s.gcr.io/heapster:v1.3.0"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8082
          initialDelaySeconds: 180
          timeoutSeconds: 5
        resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
            
        command:
          - "/heapster"
          - "--source=kubernetes.summary_api:''"

      - name: heapster-nanny
        
        image: "k8s.gcr.io/addon-resizer:1.7"
        imagePullPolicy: IfNotPresent
        resources:
            limits:
              cpu: 50m
              memory: 90Mi
            requests:
              cpu: 50m
              memory: 90Mi
            
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        command:
          - "/pod_nanny"
          - "--deployment=ulterior-oyster-heapster"
          - "--container=heapster"
          - "--cpu=150m"
          - "--extra-cpu=10m"
          - "--memory=200Mi"
          - "--extra-memory=6Mi"
          - "--threshold=5"
          - "--poll-period=300000"
