[debug] Created tunnel using local port: '42271'

[debug] SERVER: "127.0.0.1:42271"

[debug] Original chart version: ""
[debug] CHART PATH: /home/matt/go/src/k8s.io/charts/stable/aerospike

NAME:   cranky-magpie
REVISION: 1
RELEASED: Sat Jun  2 15:00:14 2018
CHART: aerospike-0.1.7
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
args: []
command: []
confFile: |-
  #default config file
  service {
      user root
      group root
      paxos-single-replica-limit 1
      pidfile /var/run/aerospike/asd.pid
      service-threads 4
      transaction-queues 4
      transaction-threads-per-queue 4
      proto-fd-max 15000
  }
  logging {
      file /var/log/aerospike/aerospike.log {
      context any info
      }

      console {
      context any info
      }
  }
  network {
      service {
      address any
      port 3000
      }
      heartbeat {
      address any
      interval 150
      #REPLACE_THIS_LINE_WITH_MESH_CONFIG
      mode mesh
      port 3002
      timeout 20
      protocol v3

      }
      fabric {
      port 3001
      }

      info {
      port 3003
      }
  }

  namespace test {
      replication-factor 2
      memory-size 1G
      default-ttl 5d
      storage-engine device {
      file /opt/aerospike/data/test.dat
      filesize 4G
      }
  }
image:
  pullPolicy: IfNotPresent
  repository: aerospike/aerospike-server
  tag: 3.14.1.2
meshService:
  annotations: {}
nodeSelector: {}
persistentVolume: {}
replicaCount: 1
resources: {}
service:
  annotations: {}
  clusterIP: None
  loadBalancerIP: null
  type: ClusterIP
terminationGracePeriodSeconds: 30

HOOKS:
MANIFEST:

---
# Source: aerospike/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cranky-magpie-aerospike
  labels:
    app: aerospike
    chart: aerospike-0.1.7
    release: cranky-magpie
    heritage: Tiller
data:
  aerospike.conf: |
    # aerospike configuration
        #default config file
    service {
        user root
        group root
        paxos-single-replica-limit 1
        pidfile /var/run/aerospike/asd.pid
        service-threads 4
        transaction-queues 4
        transaction-threads-per-queue 4
        proto-fd-max 15000
    }
    logging {
        file /var/log/aerospike/aerospike.log {
        context any info
        }
    
        console {
        context any info
        }
    }
    network {
        service {
        address any
        port 3000
        }
        heartbeat {
        address any
        interval 150
        
        mesh-seed-address-port cranky-magpie-aerospike-0.cranky-magpie-aerospike-mesh 3002
        mode mesh
        port 3002
        timeout 20
        protocol v3
    
        }
        fabric {
        port 3001
        }
    
        info {
        port 3003
        }
    }
    
    namespace test {
        replication-factor 2
        memory-size 1G
        default-ttl 5d
        storage-engine device {
        file /opt/aerospike/data/test.dat
        filesize 4G
        }
    }
---
# Source: aerospike/templates/mesh-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cranky-magpie-aerospike-mesh
  labels:
    app: aerospike
    chart: aerospike-0.1.7
    release: cranky-magpie
    heritage: Tiller
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - port: 3002
      protocol: TCP
      name: aerospike-mesh
  selector:
    app: aerospike
    release: cranky-magpie
---
# Source: aerospike/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cranky-magpie-aerospike
  labels:
    app: aerospike
    chart: aerospike-0.1.7
    release: cranky-magpie
    heritage: Tiller
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:

  clusterIP: "None"

  type: ClusterIP
  ports:
    - port: 3000
      protocol: TCP
      name: aerospike-client
    - port: 3002
      protocol: TCP
      name: aerospike-mesh
  selector:
    app: aerospike
    release: cranky-magpie
---
# Source: aerospike/templates/statefulset.yaml
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: cranky-magpie-aerospike
  labels:
    app: aerospike
    chart: aerospike-0.1.7
    release: cranky-magpie
    heritage: Tiller
spec:
  serviceName: cranky-magpie-aerospike-mesh
  replicas: 1
  template:
    metadata:
      labels:
        app: aerospike
        release: cranky-magpie
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: cranky-magpie-aerospike
        image: "aerospike/aerospike-server:3.14.1.2"
        imagePullPolicy: IfNotPresent


        ports:
        - containerPort: 3000
          name: aero-clients
        - containerPort: 3002
          name: aero-mesh
        - containerPort: 3003
          name: aero-info
        readinessProbe:
          tcpSocket:
              port: 3000
          initialDelaySeconds: 15
          timeoutSeconds: 1
        volumeMounts:
        - name: config-volume
          mountPath: /etc/aerospike
        resources:
          {}
          
      nodeSelector:
        {}
        
      volumes:
      - name: config-volume
        configMap:
          name: cranky-magpie-aerospike
          items:
          - key: aerospike.conf
            path: aerospike.conf
  volumeClaimTemplates:
