
---
# Source: elastalert/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cold-pronghorn-elastalert-config
  labels:
    app: elastalert
    chart: elastalert-0.3.0
    release: cold-pronghorn
    heritage: Tiller
data:
  elastalert_config: |-
    ---
    rules_folder: /opt/rules
    scan_subdirectories: false
    run_every:
      minutes: 1
    buffer_time:
      minutes: 15
    es_host: 
    es_port: 80
    writeback_index: elastalert_status
    use_ssl: False
    alert_time_limit:
      days: 2
---
# Source: elastalert/templates/rules.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cold-pronghorn-elastalert-rules
  labels:
    app: elastalert
    chart: elastalert-0.3.0
    release: cold-pronghorn
    heritage: Tiller
data:
