[debug] Created tunnel using local port: '42859'

[debug] SERVER: "127.0.0.1:42859"

[debug] Original chart version: ""
[debug] CHART PATH: /home/matt/go/src/k8s.io/charts/stable/kubed

NAME:   hipster-lightningbug
REVISION: 1
RELEASED: Sat Jun  2 15:00:22 2018
CHART: kubed-0.3.3
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
criticalAddon: false
imagePullPolicy: IfNotPresent
kubed:
  image: appscode/kubed
  tag: 0.4.0
logLevel: 3
nodeSelector: {}
rbac:
  create: false
  serviceAccountName: default
replicaCount: 1

HOOKS:
MANIFEST:

---
# Source: kubed/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kubed-hipster-lightningbug
  labels:
    app: "kubed"
    chart: "kubed-0.3.3"
    release: "hipster-lightningbug"
    heritage: "Tiller"
data:
  config.yaml: "YXBpU2VydmVyOgogIGFkZHJlc3M6IDo4MDgwCiAgZW5hYmxlUmV2ZXJzZUluZGV4OiB0cnVlCiAgZW5hYmxlU2VhcmNoSW5kZXg6IHRydWUKY2x1c3Rlck5hbWU6IHVuaWNvcm4KZW5hYmxlQ29uZmlnU3luY2VyOiB0cnVl"
---
# Source: kubed/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kubed-hipster-lightningbug
  labels:
    app: "kubed"
    chart: "kubed-0.3.3"
    release: "hipster-lightningbug"
    heritage: "Tiller"
spec:
  ports:
  - name: api
    port: 8080
    protocol: TCP
    targetPort: api
  - name: web
    port: 56790
    protocol: TCP
    targetPort: web
  selector:
    app: "kubed"
    release: "hipster-lightningbug"
---
# Source: kubed/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubed-hipster-lightningbug
  labels:
    chart: "kubed-0.3.3"
    app: "kubed"
    heritage: "Tiller"
    release: "hipster-lightningbug"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "kubed"
        release: "hipster-lightningbug"
    spec:
      serviceAccountName: "default"
      containers:
      - name: kubed
        args:
        - run
        - --v=3
        - --api.address=:8080
        - --web.address=:56790
        image: 'appscode/kubed:0.4.0'
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: api
          protocol: TCP
        - containerPort: 56790
          name: web
          protocol: TCP
        volumeMounts:
          - name: config
            mountPath: /srv/kubed
          - name: scratch
            mountPath: /tmp
      volumes:
        - name: config
          secret:
            secretName: kubed-hipster-lightningbug
        - name: scratch
          emptyDir: {}
