[debug] Created tunnel using local port: '33387'

[debug] SERVER: "127.0.0.1:33387"

[debug] Original chart version: ""
[debug] CHART PATH: /home/matt/go/src/k8s.io/charts/incubator/vaultingkube

NAME:   pugnacious-gecko
REVISION: 1
RELEASED: Sat Jun  2 14:59:01 2018
CHART: vaultingkube-0.1.1
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
affinity: {}
deleteOld: "true"
image:
  repository: sunshinekitty/vaultingkube
  tag: v0.1.0
nodeSelector: {}
rbac:
  create: true
replicaCount: 1
resources: {}
serviceAccount:
  create: true
  name: null
syncPeriod: "60"
tolerations: []
vaultAddress: null
vaultRootMountPath: null
vaultToken: null

HOOKS:
MANIFEST:

---
# Source: vaultingkube/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pugnacious-gecko-vaultingkube
---
# Source: vaultingkube/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pugnacious-gecko-vaultingkube
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
---
# Source: vaultingkube/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pugnacious-gecko-vaultingkube
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pugnacious-gecko-vaultingkube
subjects:
- kind: ServiceAccount
  name: pugnacious-gecko-vaultingkube
  namespace: default
