
---
# Source: sematext-docker-agent/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: telling-zebra-sematext-docker-agent
  labels:
    app: sematext-docker-agent
    chart: sematext-docker-agent-0.1.5
    release: telling-zebra
type: Opaque
data:
  spm-token: ""
  logsene-token: ""
---
# Source: sematext-docker-agent/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: telling-zebra-sematext-docker-agent
  labels:
    app: sematext-docker-agent
    chart: sematext-docker-agent-0.1.5
    release: telling-zebra
data:
  SPM_RECEIVER_URL: "https://spm-receiver.sematext.com/receiver/v1"
  LOGSENE_RECEIVER_URL: "https://logsene-receiver.sematext.com"
  EVENTS_RECEIVER_URL: "https://event-receiver.sematext.com"
