[debug] Created tunnel using local port: '36129'

[debug] SERVER: "127.0.0.1:36129"

[debug] Original chart version: ""
[debug] CHART PATH: /home/matt/go/src/k8s.io/charts/incubator/kube-registry-proxy

NAME:   cautious-squid
REVISION: 1
RELEASED: Sat Jun  2 14:58:59 2018
CHART: kube-registry-proxy-0.2.2
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
image:
  pullPolicy: IfNotPresent
  repository: k8s.gcr.io/kube-registry-proxy
  tag: 0.4
registry:
  host: gcr.io
  port: ""

HOOKS:
MANIFEST:

---
# Source: kube-registry-proxy/templates/daemon.yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: cautious-squid-kube-registry-proxy
  labels:
    heritage: "Tiller"
    release: "cautious-squid"
    chart: "kube-registry-proxy-0.2.2"
spec:
  template:
    metadata:
      name: cautious-squid-kube-registry-proxy
      labels:
        app: cautious-squid-kube-registry-proxy
    spec:
      containers:
      - name: kube-registry-proxy
        image: "k8s.gcr.io/kube-registry-proxy:0.4"
        imagePullPolicy: IfNotPresent
        env:
        - name: REGISTRY_HOST
          value: "gcr.io"
        - name: REGISTRY_PORT
          value: ""
        ports:
        - containerPort: 80
          hostPort: 5555
