
---
# Source: nginx-ldapauth-proxy/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ulterior-scorpion-nginx-ldapauth-proxy
  labels:
    app: nginx-ldapauth-proxy
    chart: nginx-ldapauth-proxy-0.1.2
    heritage: Tiller
    release: ulterior-scorpion
data:
  nginx.conf: |-
    worker_processes 10;
    worker_rlimit_nofile 16384;

    events {
        worker_connections 1024;
    }

    http {

        upstream backend-server {
            server kubernetes.default.svc.cluster.local:443;
        }

        server {

            listen 80;
            server_name ldapauth-proxy;

            error_log /var/log/nginx/error.log debug;
            access_log /var/log/nginx/access.log;

            client_max_body_size 0;

            chunked_transfer_encoding on;

            location / {
            }

            location /_ping {
                auth_basic off;
                root   /usr/share/nginx/html;
                stub_status on;
            }
        }

    }
---
# Source: nginx-ldapauth-proxy/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ulterior-scorpion-nginx-ldapauth-proxy
  labels:
    app: nginx-ldapauth-proxy
    chart: nginx-ldapauth-proxy-0.1.2
    release: ulterior-scorpion
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 80
      protocol: TCP
      name: nginx-ldapauth
  selector:
    app: nginx-ldapauth-proxy
    release: ulterior-scorpion
---
# Source: nginx-ldapauth-proxy/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ulterior-scorpion-nginx-ldapauth-proxy
  labels:
    app: nginx-ldapauth-proxy
    chart: nginx-ldapauth-proxy-0.1.2
    release: ulterior-scorpion
    heritage: Tiller
spec:
  selector:
    matchLabels:
      app: nginx-ldapauth-proxy
      release: ulterior-scorpion
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-ldapauth-proxy
        release: ulterior-scorpion
      annotations:
        checksum/config: 107b317315267cb4341b01342a4f9cb3b296bc762685d8376c61a4cb1ca62347
    spec:
      containers:
        - name: nginx-ldapauth-proxy
          image: "dweomer/nginx-auth-ldap:1.13.5-on-alpine-3.5"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /_ping
              port: 80
          readinessProbe:
            httpGet:
              path: /_ping
              port: 80
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: config
              subPath: nginx.conf
          resources:
            {}
            
      volumes:
        - name: config
          configMap:
            name: ulterior-scorpion-nginx-ldapauth-proxy
