[debug] Created tunnel using local port: '33819'

[debug] SERVER: "127.0.0.1:33819"

[debug] Original chart version: ""
[debug] CHART PATH: /home/matt/go/src/k8s.io/charts/incubator/kube-spot-termination-notice-handler

NAME:   amber-cow
REVISION: 1
RELEASED: Sat Jun  2 14:58:59 2018
CHART: kube-spot-termination-notice-handler-0.2.1
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
enableLogspout: false
image:
  pullPolicy: IfNotPresent
  repository: egeland/kube-spot-termination-notice-handler
  tag: 1.8.1-1
pollInterval: 5
rbac:
  create: true
resources: {}
serviceAccount:
  create: true
  name: null

HOOKS:
MANIFEST:

---
# Source: kube-spot-termination-notice-handler/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: amber-cow-kube-spot-termination-notice-handler
  labels:
    app: amber-cow-kube-spot-termination-notice-handler
    chart: kube-spot-termination-notice-handler
    release: amber-cow
    heritage: Tiller
---
# Source: kube-spot-termination-notice-handler/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: amber-cow-kube-spot-termination-notice-handler
  labels:
    app: amber-cow-kube-spot-termination-notice-handler
    chart: kube-spot-termination-notice-handler
    release: amber-cow
    heritage: Tiller
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - extensions
  resources:
  - replicasets
  - daemonsets
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - create
---
# Source: kube-spot-termination-notice-handler/templates/rbac.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: amber-cow-kube-spot-termination-notice-handler
  labels:
    app: amber-cow-kube-spot-termination-notice-handler
    chart: kube-spot-termination-notice-handler
    release: amber-cow
    heritage: Tiller
roleRef:
  kind: ClusterRole
  name: amber-cow-kube-spot-termination-notice-handler
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  namespace: "default"
  name: amber-cow-kube-spot-termination-notice-handler
---
# Source: kube-spot-termination-notice-handler/templates/daemonset.yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: amber-cow-kube-spot-termination-notice-handler
  labels:
    app: kube-spot-termination-notice-handler
    chart: kube-spot-termination-notice-handler-0.2.1
    release: amber-cow
    heritage: Tiller
spec:
  template:
    metadata:
      labels:
        app: kube-spot-termination-notice-handler
        release: amber-cow
    spec:
      serviceAccountName: amber-cow-kube-spot-termination-notice-handler
      containers:
        - name: kube-spot-termination-notice-handler
          image: "egeland/kube-spot-termination-notice-handler:1.8.1-1"
          imagePullPolicy: IfNotPresent
          env:
            - name: LOGSPOUT
              value: "ignore"
            - name: POLL_INTERVAL
              value: "5"
            - name: CLUSTER
              value: 
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            {}
