
---
# Source: webpagetest-agent/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: unrealistic-lamb-webpagetest-agent
  labels:
    app: webpagetest-agent
    chart: webpagetest-agent-0.1.3
    release: unrealistic-lamb
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webpagetest-agent
  template:
    metadata:
      labels:
        app: webpagetest-agent
        release: unrealistic-lamb
    spec:
      containers:
        - name: webpagetest-agent
          image: "timothyclarke/wptagent:2018-01-08"
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVER_URL
              value: "http://agent-web-page-test.local/work/"
            - name: LOCATION
              value: Test
            - name: SHAPER
              value: none
            - name: KEY
              value: SecretKey
          resources:
            {}
