[debug] Created tunnel using local port: '42059'

[debug] SERVER: "127.0.0.1:42059"

[debug] Original chart version: ""
[debug] CHART PATH: /home/matt/go/src/k8s.io/charts/incubator/webpagetest-agent

NAME:   unrealistic-lamb
REVISION: 1
RELEASED: Sat Jun  2 14:59:01 2018
CHART: webpagetest-agent-0.1.3
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
agent:
  key: SecretKey
  location: Test
  server: agent-web-page-test.local
  shaper: none
image:
  pullPolicy: IfNotPresent
  repository: timothyclarke/wptagent
  tag: 2018-01-08
replicaCount: 1
resources: {}

HOOKS:
MANIFEST:

---
# Source: webpagetest-agent/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: unrealistic-lamb-webpagetest-agent
  labels:
    app: webpagetest-agent
    chart: webpagetest-agent-0.1.3
    release: unrealistic-lamb
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webpagetest-agent
  template:
    metadata:
      labels:
        app: webpagetest-agent
        release: unrealistic-lamb
    spec:
      containers:
        - name: webpagetest-agent
          image: "timothyclarke/wptagent:2018-01-08"
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVER_URL
              value: "http://agent-web-page-test.local/work/"
            - name: LOCATION
              value: Test
            - name: SHAPER
              value: none
            - name: KEY
              value: SecretKey
          resources:
            {}
