
---
# Source: schema-registry-ui/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: muddled-wildebeest-schema-registry-ui
  labels:
    app: schema-registry-ui
    chart: schema-registry-ui-0.1.0
    release: muddled-wildebeest
    heritage: Tiller
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: schema-registry-ui
    release: muddled-wildebeest
---
# Source: schema-registry-ui/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: muddled-wildebeest-schema-registry-ui
  labels:
    app: schema-registry-ui
    chart: schema-registry-ui-0.1.0
    release: muddled-wildebeest
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry-ui
      release: muddled-wildebeest
  template:
    metadata:
      labels:
        app: schema-registry-ui
        release: muddled-wildebeest
    spec:
      containers:
        - name: schema-registry-ui
          image: "landoop/schema-registry-ui:0.9.4"
          imagePullPolicy: IfNotPresent
          env:
          - name: SCHEMAREGISTRY_URL
            value: "http://localhost:8081"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
