
---
# Source: gcloud-sqlproxy/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: pilfering-alpaca-gcloud-sqlproxy
  labels:
    app: pilfering-alpaca-gcloud-sqlproxy
    chart: "gcloud-sqlproxy-0.3.4"
    release: "pilfering-alpaca"
    heritage: "Tiller"
type: Opaque
data:
  credentials.json: |-
---
# Source: gcloud-sqlproxy/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: pilfering-alpaca-gcloud-sqlproxy
  labels:
    app: pilfering-alpaca-gcloud-sqlproxy
    chart: "gcloud-sqlproxy-0.3.4"
    release: "pilfering-alpaca"
    heritage: "Tiller"
spec:
  ports:
  - name: instance
    protocol: TCP
    port: 5432
    targetPort: instance
  selector:
    app: pilfering-alpaca-gcloud-sqlproxy
