
---
# Source: msoms/templates/omsagent-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: braided-grizzly-msoms
  labels:
    app: msoms
    chart: msoms-0.2.0
    release: braided-grizzly
    heritage: Tiller
type: Opaque
data:
  WSID: "PHlvdXJfd29ya3NwYWNlX2lkPg=="
  KEY: "PHlvdXJfd29ya3NwYWNlX2tleT4="
  DOMAIN: "b3BpbnNpZ2h0cy5henVyZS5jb20="
