
---
# Source: elastabot/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: honest-lamb-elastabot-config
  labels:
    app: elastabot
    chart: elastabot-1.1.0
    heritage: Tiller
    release: honest-lamb
data:
  elastabot.json: |-
    {
      "elasticsearch": {
        "host": "",
        "port": 9200,
        "sslEnabled": false,
        "sslStrictEnabled": false,
        "timeoutSeconds": 10,
        "urlPrefix":""
      },
      "elastalert": {
        "index": "elastalert_status",
        "silenceMinutes": 240,
        "recentMinutes": 4320
      },
      "smtp": {
        "host": "",
        "port": 25,
        "secure": false,
        "starttls": false,
        "timeoutSeconds": 4,
        "to": "",
        "from": "",
        "subjectPrefix": "",
        "debug": false
      },
      "commandPrefix": "!",
      "triageTarget": "smtp",
      "searchEnabled": "true"
    }
