[debug] Created tunnel using local port: '36713'

[debug] SERVER: "127.0.0.1:36713"

[debug] Original chart version: ""
[debug] CHART PATH: /home/matt/go/src/k8s.io/charts/stable/elasticsearch-exporter

NAME:   ignorant-walrus
REVISION: 1
RELEASED: Sat Jun  2 15:00:17 2018
CHART: elasticsearch-exporter-0.1.4
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
es:
  all: true
  indices: true
  ssl:
    ca: null
    client: null
    enabled: false
  timeout: 30s
  uri: localhost:9200
image:
  pullPolicy: IfNotPresent
  repository: justwatch/elasticsearch_exporter
  tag: 1.0.2
replicaCount: 1
resources: {}
restartPolicy: Always
service:
  annotations: {}
  httpPort: 9108
  type: ClusterIP
web:
  path: /metrics

HOOKS:
MANIFEST:

---
# Source: elasticsearch-exporter/templates/service.yaml
kind: Service
apiVersion: v1
metadata:
  name: ignorant-walrus-elasticsearch-exporter
  labels:
    chart: "elasticsearch-exporter-0.1.4"
    app: elasticsearch-exporter
    release: "ignorant-walrus"
    heritage: "Tiller"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9108
      protocol: TCP
  selector:
    app: elasticsearch-exporter
    release: "ignorant-walrus"
---
# Source: elasticsearch-exporter/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ignorant-walrus-elasticsearch-exporter
  labels:
    chart: "elasticsearch-exporter-0.1.4"
    app: elasticsearch-exporter
    release: "ignorant-walrus"
    heritage: "Tiller"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-exporter
      release: "ignorant-walrus"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: elasticsearch-exporter
        release: "ignorant-walrus"
    spec:
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: elasticsearch-exporter
          image: "justwatch/elasticsearch_exporter:1.0.2"
          imagePullPolicy: IfNotPresent
          command: ["elasticsearch_exporter",
                    "-es.uri=localhost:9200",
                    "-es.all=true",
                    "-es.indices=true",
                    "-es.timeout=30s",
                    "-web.listen-address=:9108",
                    "-web.telemetry-path=/metrics"]
          securityContext:
            capabilities:
              drop:
                - SETPCAP
                - MKNOD
                - AUDIT_WRITE
                - CHOWN
                - NET_RAW
                - DAC_OVERRIDE
                - FOWNER
                - FSETID
                - KILL
                - SETGID
                - SETUID
                - NET_BIND_SERVICE
                - SYS_CHROOT
                - SETFCAP
            readOnlyRootFilesystem: true
          resources:
            {}
            
          ports:
            - containerPort: 9108
              name: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 10
          volumeMounts:
      volumes:
