[debug] Created tunnel using local port: '41821'

[debug] SERVER: "127.0.0.1:41821"

[debug] Original chart version: ""
[debug] CHART PATH: /home/matt/go/src/k8s.io/charts/stable/spartakus

NAME:   falling-manta
REVISION: 1
RELEASED: Sat Jun  2 15:00:35 2018
CHART: spartakus-1.1.5
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
extraArgs: {}
image:
  pullPolicy: IfNotPresent
  repository: k8s.gcr.io/spartakus-amd64
  tag: v1.0.0
nodeSelector: {}
podAnnotations: {}
replicaCount: 1
resources: {}
uuid: ""

HOOKS:
MANIFEST:

---
# Source: spartakus/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: spartakus
    chart: spartakus-1.1.5
    heritage: Tiller
    release: falling-manta
  name: falling-manta-spartakus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spartakus
        release: falling-manta
    spec:
      containers:
        - name: spartakus
          image: "k8s.gcr.io/spartakus-amd64:v1.0.0"
          imagePullPolicy: "IfNotPresent"
          args:
            - volunteer
            - --cluster-id="6495da36-edf8-460d-87ab-cea8ba1f07df"
          resources:
            {}
