[debug] Created tunnel using local port: '41547'

[debug] SERVER: "127.0.0.1:41547"

[debug] Original chart version: ""
[debug] CHART PATH: /home/matt/go/src/k8s.io/charts/stable/minecraft

NAME:   vested-kudu
REVISION: 1
RELEASED: Sat Jun  2 15:00:25 2018
CHART: minecraft-0.2.1
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
image: itzg/minecraft-server
imageTag: latest
minecraftServer:
  allowNether: true
  announcePlayerAchievements: true
  difficulty: easy
  enableCommandBlock: true
  eula: "FALSE"
  forcegameMode: false
  gameMode: survival
  generateStructures: true
  generatorSettings: null
  hardcore: false
  icon: null
  jvmOpts: -Xmx512M -Xms512M
  levelSeed: null
  levelType: DEFAULT
  maxBuildHeight: 256
  maxPlayers: 20
  maxTickTime: 60000
  maxWorldSize: 10000
  motd: Welcome to Minecraft on Kubernetes!
  onlineMode: true
  ops: null
  pvp: false
  rcon:
    enabled: false
    password: CHANGEME!
    port: 25575
    serviceType: LoadBalancer
  serviceType: LoadBalancer
  spawnAnimals: true
  spawnMonsters: true
  spawnNPCs: true
  version: LATEST
  viewDistance: 10
  whitelist: null
  worldSaveName: world
persistence:
  dataDir:
    Size: 1Gi
    enabled: true
resources:
  requests:
    cpu: 500m
    memory: 512Mi

HOOKS:
MANIFEST:

---
# Source: minecraft/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: vested-kudu-minecraft
  labels:
    app: vested-kudu-minecraft
    chart: "minecraft-0.2.1"
    release: "vested-kudu"
    heritage: "Tiller"
type: Opaque
data:
  rcon-password: "Q0hBTkdFTUUh"
---
# Source: minecraft/templates/datadir-pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vested-kudu-minecraft-datadir
  labels:
    app: vested-kudu-minecraft
    chart: "minecraft-0.2.1"
    release: "vested-kudu"
    heritage: "Tiller"
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
---
# Source: minecraft/templates/minecraft-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: vested-kudu-minecraft
  labels:
    app: vested-kudu-minecraft
    chart: "minecraft-0.2.1"
    release: "vested-kudu"
    heritage: "Tiller"
spec:
  type: LoadBalancer
  ports:
  - name: minecraft
    port: 25565
    targetPort: minecraft
    protocol: TCP
  selector:
    app: vested-kudu-minecraft
