[debug] Created tunnel using local port: '35201'

[debug] SERVER: "127.0.0.1:35201"

[debug] Original chart version: ""
[debug] CHART PATH: /home/matt/go/src/k8s.io/charts/stable/bitcoind

NAME:   intended-kangaroo
REVISION: 1
RELEASED: Sat Jun  2 15:00:14 2018
CHART: bitcoind-0.1.3
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
configurationFile:
  bitcoin.conf: |-
    server=1
    printtoconsole=1
    rpcuser=rpcuser
    rpcpassword=rpcpassword
image:
  pullPolicy: IfNotPresent
  repository: arilot/docker-bitcoind
  tag: 0.15.1
persistence:
  accessMode: ReadWriteOnce
  enabled: true
  size: 300Gi
resources: {}
service:
  p2pPort: 8333
  rpcPort: 8332
  testnetP2pPort: 18333
  testnetPort: 18332

HOOKS:
MANIFEST:

---
# Source: bitcoind/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: intended-kangaroo-bitcoind
  labels:
    app: bitcoind
    chart: bitcoind-0.1.3
    release: intended-kangaroo
    heritage: Tiller
data:
  bitcoin.conf: |-
    server=1
    printtoconsole=1
    rpcuser=rpcuser
    rpcpassword=rpcpassword
---
# Source: bitcoind/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: intended-kangaroo-bitcoind
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: bitcoind
    chart: "bitcoind-0.1.3"
    release: "intended-kangaroo"
    heritage: "Tiller"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "300Gi"
---
# Source: bitcoind/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: intended-kangaroo-bitcoind
  labels:
    app: bitcoind
    chart: bitcoind-0.1.3
    release: intended-kangaroo
    heritage: Tiller
spec:
  ports:
    - name: rpc
      port: 8332
      targetPort: rpc
    - name: p2p
      port: 8333
      targetPort: p2p
    - name: testnet
      port: 18332
    - name: testnet-p2p
      port: 18333
  selector:
    app: bitcoind
    release: intended-kangaroo
---
# Source: bitcoind/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: intended-kangaroo-bitcoind
  labels:
    app: bitcoind
    chart: bitcoind-0.1.3
    release: intended-kangaroo
    heritage: Tiller
spec:
  selector:
    matchLabels:
      app: bitcoind
      release: intended-kangaroo
  template:
    metadata:
      labels:
        app: bitcoind
        release: intended-kangaroo
    spec:
      initContainers:
        - name: copy-bitcoind-config
          image: busybox
          command: ['sh', '-c', 'cp /configmap/bitcoin.conf /bitcoin/.bitcoin/bitcoin.conf']
          volumeMounts:
            - name: configmap
              mountPath: /configmap
            - name: config
              mountPath: /bitcoin/.bitcoin/
      containers:
        - name: intended-kangaroo-bitcoind
          image: "arilot/docker-bitcoind:0.15.1"
          imagePullPolicy: "IfNotPresent"
          resources:
            {}
          
          ports:
            - name: rpc
              containerPort: 8332
            - name: p2p
              containerPort: 8333
            - name: testnet
              containerPort: 18332
            - name: testnetp2pport
              containerPort: 18333
          volumeMounts:
            - name: data
              mountPath: /bitcoin
            - name: config
              mountPath: /bitcoin/.bitcoin/bitcoin.conf
              subPath: bitcoin.conf
      volumes:
        - name: config
          emptyDir: {}
        - name: configmap
          configMap:
            name: intended-kangaroo-bitcoind
        - name: data
          persistentVolumeClaim:
            claimName: intended-kangaroo-bitcoind
