
---
# Source: webpagetest-server/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fuzzy-fish-webpagetest-server
  labels:
    app: fuzzy-fish-webpagetest-server
    chart: "webpagetest-server-0.1.5"
    release: "fuzzy-fish"
    heritage: "Tiller"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
---
# Source: webpagetest-server/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fuzzy-fish-webpagetest-server
  labels:
    app: webpagetest-server
    chart: webpagetest-server-0.1.5
    release: fuzzy-fish
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: webpagetest-server
  selector:
    app: webpagetest-server
    release: fuzzy-fish
---
# Source: webpagetest-server/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: fuzzy-fish-webpagetest-server
  labels:
    app: webpagetest-server
    chart: webpagetest-server-0.1.5
    release: fuzzy-fish
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webpagetest-server
  template:
    metadata:
      labels:
        app: webpagetest-server
        release: fuzzy-fish
    spec:
      containers:
        - name: webpagetest-server
          image: "timothyclarke/wptserver:2018-01-12"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          resources:
            {}
            
          env:
          volumeMounts:
          - name: wpt-local-archive
            mountPath: /data/archive
      volumes:
      - name: wpt-local-archive
        persistentVolumeClaim:
          claimName: fuzzy-fish-webpagetest-server
