
---
# Source: mailhog/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mailhog
    chart: mailhog-2.2.0
    heritage: Tiller
    release: broken-sloth
  name: broken-sloth-mailhog
spec:
  type: "ClusterIP"
  clusterIP: ""
  ports:
    - name: http
      port: 8025
      protocol: TCP
      targetPort: http
    - name: smtp
      port: 1025
      protocol: TCP
      targetPort: smtp
  selector:
    app: mailhog
    release: broken-sloth
---
# Source: mailhog/templates/deployment.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: mailhog
    chart: mailhog-2.2.0
    heritage: Tiller
    release: broken-sloth
  name: broken-sloth-mailhog
spec:
  template:
    metadata:
      labels:
        app: mailhog
        release: broken-sloth
    spec:
      containers:
        - name: mailhog
          image: "mailhog/mailhog:v1.0.0"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: MH_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: http
              containerPort: 8025
              protocol: TCP
            - name: smtp
              containerPort: 1025
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: smtp
            initialDelaySeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            tcpSocket:
              port: smtp
          resources:
            {}
