
---
# Source: sonatype-nexus/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: viable-pronghorn-sonatype-nexus-data
  labels:
    app: sonatype-nexus
    fullname: viable-pronghorn-sonatype-nexus
    chart: sonatype-nexus-1.4.0
    release: viable-pronghorn
    heritage: Tiller
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
---
# Source: sonatype-nexus/templates/proxy-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: viable-pronghorn-sonatype-nexus
  labels:
    app: sonatype-nexus
    fullname: viable-pronghorn-sonatype-nexus
    chart: sonatype-nexus-1.4.0
    release: viable-pronghorn
    heritage: Tiller
spec:
  ports:
    - name: 
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: sonatype-nexus
    release: viable-pronghorn
  type: NodePort
---
# Source: sonatype-nexus/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: viable-pronghorn-sonatype-nexus
  labels:
    app: sonatype-nexus
    fullname: viable-pronghorn-sonatype-nexus
    chart: sonatype-nexus-1.4.0
    release: viable-pronghorn
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonatype-nexus
      release: viable-pronghorn
  template:
    metadata:
      labels:
        app: sonatype-nexus
        release: viable-pronghorn
    spec:
      containers:
        - name: nexus
          image: quay.io/travelaudience/docker-nexus:3.12.0
          imagePullPolicy: IfNotPresent
          env:
            - name: install4jAddVmParams
              value: -Xms1200M -Xmx1200M -XX:MaxDirectMemorySize=2G -XX:+UnlockExperimentalVMOptions
                -XX:+UseCGroupMemoryLimitForHeap
            
          resources:
            {}
            
          ports:
            - containerPort: 5003
              name: nexus-docker-g
            - containerPort: 8081
              name: nexus-http
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 6
          volumeMounts:
            - mountPath: /nexus-data
              name: nexus-data
            - mountPath: /nexus-data/backup
              name: nexus-backup
        - name: nexus-proxy
          image: quay.io/travelaudience/docker-nexus-proxy:2.1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: ALLOWED_USER_AGENTS_ON_ROOT_REGEX
              value: "GoogleHC"
            - name: CLOUD_IAM_AUTH_ENABLED
              value: "false"
            - name: BIND_PORT
              value: "8080"
            - name: ENFORCE_HTTPS
              value: "false"
            - name: NEXUS_DOCKER_HOST
              value: 
            - name: NEXUS_HTTP_HOST
              value: 
            - name: UPSTREAM_DOCKER_PORT
              value: "5003"
            - name: UPSTREAM_HTTP_PORT
              value: "8081"
            - name: UPSTREAM_HOST
              value: "localhost"
          ports:
            - containerPort: 8080
              name: nexus-proxy
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: viable-pronghorn-sonatype-nexus-data
        - name: nexus-backup
          emptyDir: {}
