[debug] Created tunnel using local port: '40287'

[debug] SERVER: "127.0.0.1:40287"

[debug] Original chart version: ""
[debug] CHART PATH: /home/matt/go/src/k8s.io/charts/stable/kube-lego

NAME:   jittery-emu
REVISION: 1
RELEASED: Sat Jun  2 15:00:22 2018
CHART: kube-lego-0.4.2
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
config:
  LEGO_EMAIL: foo@example.com
  LEGO_PORT: 8080
  LEGO_URL: https://acme-staging.api.letsencrypt.org/directory
image:
  pullPolicy: IfNotPresent
  repository: jetstack/kube-lego
  tag: 0.1.6
nodeSelector: {}
podAnnotations: {}
rbac:
  create: false
  serviceAccountName: default
replicaCount: 1
resources: {}

HOOKS:
MANIFEST:

---
# Source: kube-lego/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kube-lego
    chart: kube-lego-0.4.2
    heritage: Tiller
    release: jittery-emu
  name: jittery-emu-kube-lego
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-lego
        release: jittery-emu
    spec:
      serviceAccountName: "default"
      containers:
        - name: kube-lego
          image: "jetstack/kube-lego:0.1.6"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: LEGO_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LEGO_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: "LEGO_EMAIL"
              value: "foo@example.com"
            - name: "LEGO_PORT"
              value: "8080"
            - name: "LEGO_URL"
              value: "https://acme-staging.api.letsencrypt.org/directory"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources:
            {}
