[debug] Created tunnel using local port: '37913'

[debug] SERVER: "127.0.0.1:37913"

[debug] Original chart version: ""
[debug] CHART PATH: /home/matt/go/src/k8s.io/charts/stable/openebs

NAME:   elegant-ladybug
REVISION: 1
RELEASED: Sat Jun  2 15:00:28 2018
CHART: openebs-0.5.5
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
apiserver:
  affinity: {}
  image: openebs/m-apiserver
  imageTag: 0.5.3
  nodeSelector: {}
  ports:
    externalPort: 5656
    internalPort: 5656
  replicas: 1
  tolerations: {}
image:
  pullPolicy: IfNotPresent
jiva:
  image: openebs/jiva
  imageTag: 0.5.3
  replicas: 3
policies:
  monitoring:
    enabled: true
    image: openebs/m-exporter
    imageTag: 0.5.3
provisioner:
  affinity: {}
  image: openebs/openebs-k8s-provisioner
  imageTag: 0.5.3
  nodeSelector: {}
  replicas: 1
  tolerations: {}
rbac:
  create: true
serviceAccount:
  create: true
  name: null

HOOKS:
MANIFEST:

---
# Source: openebs/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elegant-ladybug-openebs
  labels:
    app: openebs
    chart: openebs-0.5.5
    release: elegant-ladybug
    heritage: Tiller
---
# Source: openebs/templates/crd-sp.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: storagepools.openebs.io
  labels:
    app: openebs
    chart: openebs-0.5.5
    release: elegant-ladybug
    heritage: Tiller
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: openebs.io
  # version name to use for REST API: /apis/<group>/<version>
  version: v1alpha1
  # either Namespaced or Cluster
  scope: Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: storagepools
    # singular name to be used as an alias on the CLI and for display
    singular: storagepool
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: StoragePool
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - sp
---
# Source: openebs/templates/crd-spc.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: storagepoolclaims.openebs.io
  labels:
    app: openebs
    chart: openebs-0.5.5
    release: elegant-ladybug
    heritage: Tiller
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: openebs.io
  # version name to use for REST API: /apis/<group>/<version>
  version: v1alpha1
  # either Namespaced or Cluster
  scope: Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: storagepoolclaims
    # singular name to be used as an alias on the CLI and for display
    singular: storagepoolclaim
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: StoragePoolClaim
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - spc
---
# Source: openebs/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: elegant-ladybug-openebs
  labels:
    app: openebs
    chart: openebs-0.5.5
    release: elegant-ladybug
    heritage: Tiller
rules:
- apiGroups: ["*"]
  resources: ["nodes","nodes/proxy"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["*"]
  resources: ["namespaces", "services", "pods", "deployments", "events", "endpoints"]
  verbs: ["*"]
- apiGroups: ["*"]
  resources: ["persistentvolumes","persistentvolumeclaims"]
  verbs: ["*"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["*"]
- apiGroups: ["*"]
  resources: ["storagepools"]
  verbs: ["get", "list"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
# Source: openebs/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: elegant-ladybug-openebs
  labels:
    app: openebs
    chart: openebs-0.5.5
    release: elegant-ladybug
    heritage: Tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: elegant-ladybug-openebs
subjects:
- kind: ServiceAccount
  name: elegant-ladybug-openebs
  namespace: default
---
# Source: openebs/templates/service-maya-apiserver.yaml
apiVersion: v1
kind: Service
metadata:
  name: elegant-ladybug-openebs-apiservice
  labels:
    app: openebs
    chart: openebs-0.5.5
    release: elegant-ladybug
    heritage: Tiller
spec:
  ports:
  - name: api
    port: 5656
    targetPort: 5656
    protocol: TCP
  selector:
    app: openebs
    release: elegant-ladybug
    component: apiserver
  sessionAffinity: None
---
# Source: openebs/templates/deployment-maya-apiserver.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: elegant-ladybug-openebs-apiserver
  labels:
    app: openebs
    chart: openebs-0.5.5
    release: elegant-ladybug
    heritage: Tiller
    component: apiserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openebs
        release: elegant-ladybug
        component: apiserver
    spec:
      serviceAccountName: elegant-ladybug-openebs
      containers:
      - name: openebs-apiserver
        image: "openebs/m-apiserver:0.5.3"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5656
        env:
        # OPENEBS_IO_KUBE_CONFIG enables maya api service to connect to K8s
        # based on this config. This is ignored if empty.
        # This is supported for maya api server version 0.5.2 onwards
        #- name: OPENEBS_IO_KUBE_CONFIG
        #  value: "/home/ubuntu/.kube/config"
        # OPENEBS_IO_K8S_MASTER enables maya api service to connect to K8s
        # based on this address. This is ignored if empty.
        # This is supported for maya api server version 0.5.2 onwards
        #- name: OPENEBS_IO_K8S_MASTER
        #  value: "http://172.28.128.3:8080"
        - name: OPENEBS_IO_JIVA_CONTROLLER_IMAGE
          value: "openebs/jiva:0.5.3"
        - name: OPENEBS_IO_JIVA_REPLICA_IMAGE
          value: "openebs/jiva:0.5.3"
        - name: OPENEBS_IO_VOLUME_MONITOR_IMAGE
          value: "openebs/m-exporter:0.5.3"
        - name: OPENEBS_IO_JIVA_REPLICA_COUNT
          value: "3"
---
# Source: openebs/templates/deployment-maya-provisioner.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: elegant-ladybug-openebs-provisioner
  labels:
    app: openebs
    chart: openebs-0.5.5
    release: elegant-ladybug
    heritage: Tiller
    component: provisioner
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openebs
        release: elegant-ladybug
        component: provisioner
    spec:
      serviceAccountName: elegant-ladybug-openebs
      containers:
      - name: openebs-provisioner
        image: "openebs/openebs-k8s-provisioner:0.5.3"
        imagePullPolicy: IfNotPresent
        env:
        # OPENEBS_IO_K8S_MASTER enables openebs provisioner to connect to K8s
        # based on this address. This is ignored if empty.
        # This is supported for openebs provisioner version 0.5.2 onwards
        #- name: OPENEBS_IO_K8S_MASTER
        #  value: "http://10.128.0.12:8080"
        # OPENEBS_IO_KUBE_CONFIG enables openebs provisioner to connect to K8s
        # based on this config. This is ignored if empty.
        # This is supported for openebs provisioner version 0.5.2 onwards
        #- name: OPENEBS_IO_KUBE_CONFIG
        #  value: "/home/ubuntu/.kube/config"
        # OPENEBS_NAMESPACE is the namespace that this provisioner will
        # lookup to find maya api service
        - name: OPENEBS_NAMESPACE
          value: "default"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        # OPENEBS_MAYA_SERVICE_NAME provides the maya-apiserver K8s service name,
        # that provisioner should forward the volume creaet/delete requests.
        # If not present, "maya-apiserver-service" will be used for lookup.
        # This is supported for openebs provisioner version 0.5.3-RC1 onwards
        - name: OPENEBS_MAYA_SERVICE_NAME
          value: "elegant-ladybug-openebs-apiservice"
        # The following values will be set as annotations to the PV object.
        # Refer : https://github.com/openebs/external-storage/pull/15
        #- name: OPENEBS_MONITOR_URL
        #  value: ""
        #- name: OPENEBS_MONITOR_VOLKEY
        #  value: ""
        #- name: MAYA_PORTAL_URL
        #  value: ""
