[debug] Created tunnel using local port: '35441'

[debug] SERVER: "127.0.0.1:35441"

[debug] Original chart version: ""
[debug] CHART PATH: /home/matt/go/src/k8s.io/charts/stable/dask-distributed

NAME:   intent-angelfish
REVISION: 1
RELEASED: Sat Jun  2 15:00:16 2018
CHART: dask-distributed-2.0.2
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
jupyter:
  component: jupyter-notebook
  containerPort: 8888
  image: jupyter/base-notebook
  imageTag: 11be019e4079
  name: jupyter
  password: sha1:aae8550c0a44:9507d45e087d5ee481a5ce9f4f16f37a0867318c
  replicas: 1
  resources: {}
  servicePort: 80
  serviceType: LoadBalancer
scheduler:
  component: dask-scheduler
  containerPort: 8786
  image: daskdev/dask
  imageTag: latest
  name: scheduler
  replicas: 1
  resources: {}
  servicePort: 8786
  serviceType: LoadBalancer
webUI:
  containerPort: 8787
  name: webui
  servicePort: 80
worker:
  component: dask-worker
  containerPort: 8081
  image: daskdev/dask
  imageTag: latest
  name: worker
  replicas: 3
  resources: {}

HOOKS:
MANIFEST:

---
# Source: dask-distributed/templates/dask-jupyter-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: intent-angelfish-jupyter-config
  labels:
    app: dask-distributed
    heritage: "Tiller"
    release: "intent-angelfish"
    chart: "dask-distributed-2.0.2"
    component: "intent-angelfish-jupyter-notebook"
data:
  jupyter_notebook_config.py: |
    c = get_config()
    c.NotebookApp.password = 'sha1:aae8550c0a44:9507d45e087d5ee481a5ce9f4f16f37a0867318c'
---
# Source: dask-distributed/templates/dask-jupyter-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: intent-angelfish-jupyter
  labels:
    app: dask-distributed
    heritage: "Tiller"
    release: "intent-angelfish"
    chart: "dask-distributed-2.0.2"
    component: "intent-angelfish-jupyter-notebook"
spec:
  ports:
    - port: 80
      targetPort: 8888
  selector:
    app: dask-distributed
    release: "intent-angelfish"
    component: "intent-angelfish-jupyter-notebook"
  type: LoadBalancer
---
# Source: dask-distributed/templates/dask-scheduler-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: intent-angelfish-schedul
  labels:
    app: dask-distributed
    heritage: "Tiller"
    release: "intent-angelfish"
    chart: "dask-distributed-2.0.2"
    component: "intent-angelfish-dask-scheduler"
spec:
  ports:
    - name: intent-angelfish-schedul
      port: 8786
      targetPort: 8786
    - name: intent-angelfish-webui
      port: 80
      targetPort: 8787
  selector:
    app: dask-distributed
    release: "intent-angelfish"
    component: "intent-angelfish-dask-scheduler"
  type: LoadBalancer
---
# Source: dask-distributed/templates/dask-jupyter-deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: intent-angelfish-jupyter
  labels:
    app: dask-distributed
    heritage: "Tiller"
    release: "intent-angelfish"
    chart: "dask-distributed-2.0.2"
    component: "intent-angelfish-jupyter-notebook"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dask-distributed
        release: "intent-angelfish"
        component: "intent-angelfish-jupyter-notebook"
    spec:
      containers:
        - name: intent-angelfish-jupyter
          image: "jupyter/base-notebook:11be019e4079"
          ports:
            - containerPort: 8888
          resources:
            {}
            
          volumeMounts:
          - name: config-volume
            mountPath: /home/jovyan/.jupyter
      volumes:
      - name: config-volume
        configMap:
          name: intent-angelfish-jupyter-config
---
# Source: dask-distributed/templates/dask-scheduler-deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: intent-angelfish-schedul
  labels:
    app: dask-distributed
    heritage: "Tiller"
    release: "intent-angelfish"
    chart: "dask-distributed-2.0.2"
    component: "intent-angelfish-dask-scheduler"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dask-distributed
        release: "intent-angelfish"
        component: "intent-angelfish-dask-scheduler"
    spec:
      containers:
        - name: intent-angelfish-schedul
          image: "daskdev/dask:latest"
          command: ["dask-scheduler", "--port", "8786", "--bokeh-port", "8787"]
          ports:
            - containerPort: 8786
            - containerPort: 8787
          resources:
            {}
---
# Source: dask-distributed/templates/dask-worker-deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: intent-angelfish-worker
  labels:
    app: dask-distributed
    heritage: "Tiller"
    release: "intent-angelfish"
    chart: "dask-distributed-2.0.2"
    component: "intent-angelfish-dask-worker"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dask-distributed
        release: "intent-angelfish"
        component: "intent-angelfish-dask-worker"
    spec:
      containers:
        - name: intent-angelfish-worker
          image: "daskdev/dask:latest"
          command: ["dask-worker", "intent-angelfish-schedul:8786"]
          ports:
            - containerPort: 8081
          resources:
            {}
