[debug] Created tunnel using local port: '38267'

[debug] SERVER: "127.0.0.1:38267"

[debug] Original chart version: ""
[debug] CHART PATH: /home/matt/go/src/k8s.io/charts/stable/cert-manager

NAME:   affable-owl
REVISION: 1
RELEASED: Sat Jun  2 15:00:14 2018
CHART: cert-manager-v0.3.1
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
certificateResourceShortNames:
- cert
- certs
clusterResourceNamespace: ""
createCustomResource: true
createNamespaceResource: false
extraArgs: []
image:
  pullPolicy: IfNotPresent
  repository: quay.io/jetstack/cert-manager-controller
  tag: v0.3.0
ingressShim: {}
leaderElection:
  namespace: ""
nodeSelector: {}
podAnnotations: {}
podLabels: {}
rbac:
  create: true
replicaCount: 1
resources: {}
serviceAccount:
  create: true
  name: null

HOOKS:
MANIFEST:

---
# Source: cert-manager/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-affable-owl
  namespace: "default"
  labels:
    app: cert-manager
    chart: cert-manager-v0.3.1
    release: affable-owl
    heritage: Tiller
---
# Source: cert-manager/templates/certificate-crd.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: certificates.certmanager.k8s.io
  labels:
    app: cert-manager
    chart: cert-manager-v0.3.1
    release: affable-owl
    heritage: Tiller
spec:
  group: certmanager.k8s.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Certificate
    plural: certificates
    shortNames:
      - cert
      - certs
---
# Source: cert-manager/templates/clusterissuer-crd.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterissuers.certmanager.k8s.io
  labels:
    app: cert-manager
    chart: cert-manager-v0.3.1
    release: affable-owl
    heritage: Tiller
spec:
  group: certmanager.k8s.io
  version: v1alpha1
  names:
    kind: ClusterIssuer
    plural: clusterissuers
  scope: Cluster
---
# Source: cert-manager/templates/issuer-crd.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: issuers.certmanager.k8s.io
  labels:
    app: cert-manager
    chart: cert-manager-v0.3.1
    release: affable-owl
    heritage: Tiller
spec:
  group: certmanager.k8s.io
  version: v1alpha1
  names:
    kind: Issuer
    plural: issuers
  scope: Namespaced
---
# Source: cert-manager/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cert-manager-affable-owl
  labels:
    app: cert-manager
    chart: cert-manager-v0.3.1
    release: affable-owl
    heritage: Tiller
rules:
  - apiGroups: ["certmanager.k8s.io"]
    resources: ["certificates", "issuers", "clusterissuers"]
    verbs: ["*"]
  - apiGroups: [""]
    # TODO: remove endpoints once 0.4 is released. We include it here in case
    # users use the 'master' version of the Helm chart with a 0.2.x release of
    # cert-manager that still performs leader election with Endpoint resources.
    # We advise users don't do this, but some will anyway and this will reduce
    # friction.
    resources: ["endpoints", "configmaps", "secrets", "events", "services", "pods"]
    verbs: ["*"]
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["*"]
---
# Source: cert-manager/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-affable-owl
  labels:
    app: cert-manager
    chart: cert-manager-v0.3.1
    release: affable-owl
    heritage: Tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-affable-owl
subjects:
  - name: cert-manager-affable-owl
    namespace: "default"
    kind: ServiceAccount
---
# Source: cert-manager/templates/deployment.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cert-manager-affable-owl
  namespace: "default"
  labels:
    app: cert-manager
    chart: cert-manager-v0.3.1
    release: affable-owl
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-manager
      release: affable-owl
  template:
    metadata:
      labels:
        app: cert-manager
        release: affable-owl
      annotations:
    spec:
      serviceAccountName: cert-manager-affable-owl
      containers:
        - name: cert-manager
          image: "quay.io/jetstack/cert-manager-controller:v0.3.0"
          imagePullPolicy: IfNotPresent
          args:
          - --cluster-resource-namespace=$(POD_NAMESPACE)
          - --leader-election-namespace=$(POD_NAMESPACE)
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          resources:
            {}
