
---
# Source: newrelic-infrastructure/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: newrelic-infrastructure
    chart: newrelic-infrastructure-0.4.0
    heritage: "Tiller"
    release: "wishing-chimp"
  name: wishing-chimp-newrelic-infrastructure
---
# Source: newrelic-infrastructure/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:     
    app: newrelic-infrastructure
    chart: newrelic-infrastructure-0.4.0
    heritage: Tiller
    release: wishing-chimp
  name: wishing-chimp-newrelic-infrastructure
rules:
- apiGroups: [""]
  resources:
    - "nodes"
    - "nodes/stats"
    - "nodes/proxy"
    - "pods"
    - "services"
  verbs: ["get", "list"]
---
# Source: newrelic-infrastructure/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:     
    app: newrelic-infrastructure
    chart: newrelic-infrastructure-0.4.0
    heritage: Tiller
    release: wishing-chimp
  name: wishing-chimp-newrelic-infrastructure
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wishing-chimp-newrelic-infrastructure
subjects:
- kind: ServiceAccount
  name: wishing-chimp-newrelic-infrastructure
  namespace: default
