[debug] Created tunnel using local port: '37805'

[debug] SERVER: "127.0.0.1:37805"

[debug] Original chart version: ""
[debug] CHART PATH: /home/matt/go/src/k8s.io/charts/stable/prometheus-pushgateway

NAME:   jittery-orangutan
REVISION: 1
RELEASED: Sat Jun  2 15:00:31 2018
CHART: prometheus-pushgateway-0.1.2
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
affinity: {}
extraArgs: []
image:
  pullPolicy: IfNotPresent
  repository: prom/pushgateway
  tag: v0.4.0
ingress:
  enabled: false
nodeSelector: {}
podAnnotations: {}
replicaCount: 1
resources: {}
service:
  port: 9091
  targetPort: 9091
  type: ClusterIP
serviceAccount:
  create: true
  name: null
tolerations: {}

HOOKS:
MANIFEST:

---
# Source: prometheus-pushgateway/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jittery-orangutan-prometheus-pushgateway
  labels:
    app: prometheus-pushgateway
    chart: prometheus-pushgateway-0.1.2    
    release: "jittery-orangutan"
    heritage: "Tiller"
---
# Source: prometheus-pushgateway/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: jittery-orangutan-prometheus-pushgateway
  labels:
    app: prometheus-pushgateway
    chart: prometheus-pushgateway-0.1.2
    release: jittery-orangutan
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 9091
      targetPort: 9091
      protocol: TCP
      name: http
  selector:
    app: prometheus-pushgateway
    release: jittery-orangutan
---
# Source: prometheus-pushgateway/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: jittery-orangutan-prometheus-pushgateway
  labels:
    app: prometheus-pushgateway
    chart: prometheus-pushgateway-0.1.2
    release: jittery-orangutan
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-pushgateway
      release: jittery-orangutan
  template:
    metadata:
      labels:
        app: prometheus-pushgateway
        release: jittery-orangutan
      annotations:
        {}
                
    spec:
      serviceAccountName: jittery-orangutan-prometheus-pushgateway
      containers:
        - name: pushgateway
          image: "prom/pushgateway:v0.4.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 9091
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /#/status
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /#/status
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
          resources:
            {}
