[debug] Created tunnel using local port: '46233'

[debug] SERVER: "127.0.0.1:46233"

[debug] Original chart version: ""
[debug] CHART PATH: /home/matt/go/src/k8s.io/charts/stable/memcached

NAME:   newbie-platypus
REVISION: 1
RELEASED: Sat Jun  2 15:00:25 2018
CHART: memcached-2.1.1
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
AntiAffinity: hard
image: memcached:1.5.6-alpine
memcached:
  extendedOptions: modern
  maxItemMemory: 64
  verbosity: v
pdbMinAvailable: 3
replicaCount: 3
resources:
  requests:
    cpu: 50m
    memory: 64Mi

HOOKS:
MANIFEST:

---
# Source: memcached/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: newbie-platypus-memcached
  labels:
    app: newbie-platypus-memcached
    chart: "memcached-2.1.1"
    release: "newbie-platypus"
    heritage: "Tiller"
spec:
  clusterIP: None
  ports:
  - name: memcache
    port: 11211
    targetPort: memcache
  selector:
    app: newbie-platypus-memcached
---
# Source: memcached/templates/statefulset.yaml
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: newbie-platypus-memcached
  labels:
    app: newbie-platypus-memcached
    chart: "memcached-2.1.1"
    release: "newbie-platypus"
    heritage: "Tiller"
spec:
  serviceName: newbie-platypus-memcached
  replicas: 3
  template:
    metadata:
      labels:
        app: newbie-platypus-memcached
        chart: "memcached-2.1.1"
        release: "newbie-platypus"
        heritage: "Tiller"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                app:  newbie-platypus-memcached
                release: "newbie-platypus"
      containers:
      - name: newbie-platypus-memcached
        image: memcached:1.5.6-alpine
        imagePullPolicy: ""
        command:
        - memcached
        - -m 64
        - -o
        - modern
        - -v
        ports:
        - name: memcache
          containerPort: 11211
        livenessProbe:
          tcpSocket:
            port: memcache
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: memcache
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
---
# Source: memcached/templates/pdb.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: newbie-platypus-memcached
spec:
  selector:
    matchLabels:
      app: newbie-platypus-memcached
      chart: "memcached-2.1.1"
      release: "newbie-platypus"
      heritage: "Tiller"
  minAvailable: 3
