[debug] Created tunnel using local port: '46519'

[debug] SERVER: "127.0.0.1:46519"

[debug] Original chart version: ""
[debug] CHART PATH: /home/matt/go/src/k8s.io/charts/stable/metabase

NAME:   lopsided-bunny
REVISION: 1
RELEASED: Sat Jun  2 15:00:25 2018
CHART: metabase-0.4.1
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
database:
  type: h2
emojiLogging: true
image:
  pullPolicy: IfNotPresent
  repository: metabase/metabase
  tag: v0.27.2
ingress:
  annotations: null
  enabled: false
  hosts: null
  tls: null
listen:
  host: 0.0.0.0
  port: 3000
password:
  complexity: normal
  length: 6
replicaCount: 1
resources: {}
service:
  annotations: null
  externalPort: 80
  internalPort: 3000
  name: metabase
  type: ClusterIP
ssl:
  enabled: false
timeZone: UTC

HOOKS:
MANIFEST:

---
# Source: metabase/templates/database-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: lopsided-bunny-metabase-database
  labels:
    app: metabase
    chart: metabase-0.4.1
    release: lopsided-bunny
    heritage: Tiller
type: Opaque
data:
---
# Source: metabase/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: lopsided-bunny-metabase
  labels:
    app: metabase
    chart: metabase-0.4.1
    release: lopsided-bunny
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: metabase
  selector:
    app: metabase
    release: lopsided-bunny
---
# Source: metabase/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lopsided-bunny-metabase
  labels:
    app: metabase
    chart: metabase-0.4.1
    release: lopsided-bunny
    heritage: Tiller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: metabase
        release: lopsided-bunny
    spec:
      containers:
        - name: metabase
          image: "metabase/metabase:v0.27.2"
          imagePullPolicy: IfNotPresent
          env:
          - name: MB_JETTY_HOST
            value: "0.0.0.0"
          - name: MB_JETTY_PORT
            value: "3000"
          - name: MB_DB_TYPE
            value: h2
          - name: MB_PASSWORD_COMPLEXITY
            value: normal
          - name: MB_PASSWORD_LENGTH
            value: "6"
          - name: JAVA_TIMEZONE
            value: UTC
          - name: MB_EMOJI_IN_LOGS
            value: "true"
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 120
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 5
          resources:
            {}
